package Form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hades
 */
import background.autoresize_tabel;
import koneksi.Koneksi.*;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;
public class data_datang extends javax.swing.JInternalFrame {

    /**
     * Creates new form penduduk
     */
    public data_datang()   {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        autonumber();
        data_tabel();
        lebarKolom();
        
        
        
        data_tabel_datang2();
        lebarkolom3();
        
       
        
        
      
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private String no_datang,no_kk,stts_kk_p,nik_pemohon,alamat_asal,rt_asal,rw_asal,desa_asal,
              kec_asal,kab_asal,prov_asal,kode_pos_asal,tgl_datang,jenis_pindah,stts,nama,no;
      
      private home frame= new home();
      
      private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"No Pendatang","No KK","Status KK","Nik Pemohon",
                 "Alamat Asal","Rt Asal","Rw Asal","Desa Asal",
                 "Kecamatan Asal","Kabupaten Asal","Provinsi Asal",
                  "Kode Pos Asal","Tanggal Datang","Jenis Kedatangan"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,false,false,false,false,false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
       private void cari_penduduk(String kondisi1){
           no_kk=txt_kk.getText();
        try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari1.getText();
                     
                    ResultSet next_row = st.executeQuery("SELECT nik,no_kk,nama,stts FROM penduduk WHERE "+kondisi1+" like '%"+search+"%' AND stts='kosong' and no_kk='"+no_kk+"'");
                   

                    tabelModel_penduduk.setRowCount(0);
                    String [] data = new String[4];
                    int i = 1;

                    while(next_row.next())
                    {
                        data[0]=next_row.getString("nik");
                        data[1]=next_row.getString("no_kk");
                        data[2]=next_row.getString("nama");
                        data[3]=next_row.getString("stts");

                        tabelModel_penduduk.addRow(data);
                        i++;
                    }
                    next_row.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
    
    
    }
      
      
      
   private javax.swing.table.DefaultTableModel getDefaultpenduduk(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"Nik","No KK","Nama","Status"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
   
   private javax.swing.table.DefaultTableModel getDefaultdatang(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"No","No Pendatang","Nik"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
   
   
    
    private javax.swing.table.DefaultTableModel tabelModel=getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel tabelModel_dialog=getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel tabelModel_penduduk=getDefaultpenduduk();
    private javax.swing.table.DefaultTableModel tabelModel_keluarga_datang=getDefaultdatang();
    
    
    
    
    
    
    private void lebarKolom() {
        TableColumn lebar_kolom;

        

        lebar_kolom = tabel_datang.getColumnModel().getColumn(0);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(1);
        lebar_kolom.setPreferredWidth(130);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(3);
        lebar_kolom.setPreferredWidth(130);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(4);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(5);
        lebar_kolom.setPreferredWidth(70);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(6);
        lebar_kolom.setPreferredWidth(70);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(7);
        lebar_kolom.setPreferredWidth(90);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(8);
        lebar_kolom.setPreferredWidth(90);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(9);
        lebar_kolom.setPreferredWidth(90);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(10);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(11);
        lebar_kolom.setPreferredWidth(50);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(12);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_datang.getColumnModel().getColumn(13);
        lebar_kolom.setPreferredWidth(250);
        
        lebar_kolom.setPreferredWidth(200);


        

    }  
    
    private void lebarkolom2(){
    
        TableColumn lebar_kolom;
        lebar_kolom = tabel_cari_penduduk.getColumnModel().getColumn(0);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_cari_penduduk.getColumnModel().getColumn(1);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_cari_penduduk.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_cari_penduduk.getColumnModel().getColumn(3);
        lebar_kolom.setPreferredWidth(80);
    
    }
    
    private void lebarkolom3(){
    
        TableColumn lebar_kolom;
        lebar_kolom = tabel_keluarga_datang.getColumnModel().getColumn(0);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_keluarga_datang.getColumnModel().getColumn(1);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_keluarga_datang.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(150);
    }

    
    private void data_tabel_penduduk(){
        tabel_cari_penduduk.setAutoResizeMode(tabel_cari_penduduk.AUTO_RESIZE_OFF);    
        tabel_cari_penduduk.setModel(tabelModel_penduduk);
        no_kk=txt_kk.getText();
        
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet res=state.executeQuery("SELECT nik,no_kk,nama,stts "
                    + "from penduduk where stts='kosong' and no_kk='"+no_kk+"'");
            
            String[] kolom={"Nik","No KK","Nama","Status"};
            tabelModel_penduduk.setDataVector(null,kolom);
            while(res.next()){
                tabelModel_penduduk.addRow(new Object[]{
                    res.getString("nik"),
                    res.getString("no_kk"),
                    res.getString("nama"),
                    res.getString("stts"),
                });
            }
        
        
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane,""+e);
        }
        //new autoresize_tabel().Kolom(tabel_cari_penduduk);
        tabel_cari_penduduk.revalidate();
       
    }
    
    
    private void data_tabel_datang1(){
       tabel_keluarga_datang.setAutoResizeMode(tabel_keluarga_datang.AUTO_RESIZE_OFF);    
        tabel_keluarga_datang.setModel(tabelModel_keluarga_datang);
        String datang=txt_datang_1.getText();
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet res=state.executeQuery("SELECT * from detail_pendatang where no_pendatang='"+datang+"'");
            
            String[] kolom={"No","No Datang","NIK"};
            tabelModel_keluarga_datang.setDataVector(null,kolom);
            while(res.next()){
                tabelModel_keluarga_datang.addRow(new Object[]{
                    res.getString("no"),
                    res.getString("no_pendatang"),
                    res.getString("nik"),
                });
            }
        
        
        }catch (Exception e){
            
            if(e!=null){
                JOptionPane.showMessageDialog(rootPane,"Keluarga Yang di pilih belum ada");
                JOptionPane.showMessageDialog(rootPane,""+e);
            }
            //JOptionPane.showMessageDialog(rootPane,""+e);
        }
      // new autoresize_tabel().Kolom(tabel_keluarga_datang);
        tabel_keluarga_datang.revalidate();
       
    }
    
       private void data_tabel_datang2(){
        tabel_keluarga_datang.setAutoResizeMode(tabel_keluarga_datang.AUTO_RESIZE_OFF);    
        tabel_keluarga_datang.setModel(tabelModel_keluarga_datang);
        String datang=txt_datang_1.getText();
        
            
            String[] kolom={"No","No Datang","NIK"};
            tabelModel_keluarga_datang.setDataVector(null,kolom);
            
               
            
        
        
        
        //new autoresize_tabel().Kolom(tabel_keluarga_datang);
        tabel_keluarga_datang.revalidate();
       
    }
    
    
    
    
    
private void data_tabel(){
tabel_datang.setAutoResizeMode(tabel_datang.AUTO_RESIZE_OFF);    
tabel_datang.setModel(tabelModel);
try{
Statement state=(Statement)Koneksi.koneksi().createStatement();
ResultSet res=state.executeQuery("SELECT no_pendatang,no_kk,stt_kk_p,nik_pemohon,"
        + "alamat_asal,rt_asal,rw_asal,desa_asal,kecamatan_asal,"
        + "kab_asal,prov_asal,kode_pos_asal,tgl_datang,"
        + "CASE WHEN jenis_kepindahan='1' THEN 'Kepala keluarga'"
        + "WHEN jenis_kepindahan='2' THEN 'Kep. keluarga dan seluruh anggota'"
        + "WHEN jenis_kepindahan='3' THEN 'Kep. keluarga dan sebagian anggota'"
        + "WHEN jenis_kepindahan='4' THEN 'Anggota keluarga'"
        + "END AS jenis_kedatangan FROM data_pendatang");

String[] colom={"No Pendatang","No KK","Status KK","Nik Pemohon",
                 "Alamat Asal","Rt Asal","Rw Asal","Desa Asal",
                 "Kecamatan Asal","Kabupaten Asal","Provinsi Asal",
                  "Kode Pos Asal","Tanggal Datang","Jenis Kedatangan"};
tabelModel.setDataVector(null,colom);
while(res.next())
{
tabelModel.addRow(new Object[]{
res.getString("no_pendatang"),
res.getString("no_kk"),
res.getString("stt_kk_p"),
res.getString("nik_pemohon"),
res.getString("alamat_asal"),
res.getString("rt_asal"),
res.getString("rw_asal"),
res.getString("desa_asal"),
res.getString("kecamatan_asal"),
res.getString("kab_asal"),
res.getString("prov_asal"),
res.getString("kode_pos_asal"),
res.getString("tgl_datang"),
res.getString("jenis_kedatangan"),

});

}
}catch (Exception e){
JOptionPane.showMessageDialog(rootPane,""+e);
}
new autoresize_tabel().Kolom(tabel_datang);
tabel_datang.revalidate(); 
}
    
    public void data_tabel_jdialog(){
        jTable1.setModel(tabelModel_dialog);
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("select * from penduduk where stts='kosong'");
            String [] kolom={"NIK","No KK","Nama"};
            tabelModel_dialog.setDataVector(null, kolom);
            
             while(next_row.next()){
                 tabelModel_dialog.addRow(new Object[] {
                 next_row.getString("nik"),    
                 next_row.getString("no_kk"),
                 next_row.getString("nama"),
                 
                 
                 });
             }
             
        }catch(Exception e){
    
        }
    }
    private void simpan(){
    no_datang=txt_datang.getText();
    no_kk=txt_kk.getText();
    if(cmb_status_kk.getSelectedItem().equals("Numpang KK")){
        stts_kk_p="Numpang KK";
    }
    
    else if(cmb_status_kk.getSelectedItem().equals("Membuat KK baru")){
        stts_kk_p="Membuat KK baru";
    }
    
    else if(cmb_status_kk.getSelectedItem().equals("Nomor KK tetap")){
        stts_kk_p="Nomor KK tetap";
    }
    
    nik_pemohon=txt_nik_mohon.getText();
    alamat_asal=txt_alamat.getText();
    rt_asal=txt_rt.getText();
    rw_asal=txt_rw.getText();
    desa_asal=txt_desa.getText();
    kec_asal=txt_kec.getText();
    kab_asal=txt_kab.getText();
    prov_asal=txt_prov.getText();
    kode_pos_asal=txt_kode_pos.getText();
    
        String tampil_tgl="yyyy-MM-dd";
        Calendar cal=dateChooserCombo1.getSelectedDate();
        SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
        tgl_datang=String.valueOf(format1.format(cal.getTime()));
    
    if(cmb_jenis_kedatangan.getSelectedItem().equals("Kepala keluarga")){
        jenis_pindah="1";
    }
    else if(cmb_jenis_kedatangan.getSelectedItem().equals("Kep. keluarga dan seluruh anggota")){
        jenis_pindah="2";
    }
    
    else if(cmb_jenis_kedatangan.getSelectedItem().equals("Kep. keluarga dan sebagian anggota")){
        jenis_pindah="3";
    }
    
    else if(cmb_jenis_kedatangan.getSelectedItem().equals("Anggota keluarga")){
        jenis_pindah="4";
    }
    try{
        Statement statement =(Statement)Koneksi.koneksi().createStatement();
        statement.executeUpdate("insert into data_pendatang values('"
            +no_datang+"','"
            +no_kk+"','"
            +stts_kk_p+"','"
            +nik_pemohon+"','"
            +alamat_asal+"','"
            +rt_asal+"','"
            +rw_asal+"','"
            +desa_asal+"','"
            +kec_asal+"','"
            +kab_asal+"','"
            +prov_asal+"','"
            +kode_pos_asal+"','"
            +tgl_datang+"','"    
            +jenis_pindah+"');");

        statement.close();
        JOptionPane.showMessageDialog(null,"Data Telah Disimpan....");
        clean();
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,""+e);
        }
              
  
    }
    
    private void clean(){
        txt_datang.setText("");
        autonumber();
        txt_kk.setText("");
        cmb_status_kk.setSelectedItem("--Status KK--");
        txt_nik_mohon.setText("");
        txt_alamat.setText("");
        txt_rt.setText("");
        txt_rw.setText("");
        txt_desa.setText("");
        txt_kec.setText("");
        txt_kab.setText("");
        txt_prov.setText("");
        txt_kode_pos.setText("");
        cmb_jenis_kedatangan.setSelectedItem("--Jenis Kedatangan--");
        
        
        
       jButton1.setText("save");
    
    }
    
    
private void update(){
    no_datang=txt_datang.getText();
    no_kk=txt_kk.getText();
    if(cmb_status_kk.getSelectedItem().equals("Numpang KK")){
        stts_kk_p="Numpang KK";
    }
    
    else if(cmb_status_kk.getSelectedItem().equals("Membuat KK baru")){
        stts_kk_p="Membuat KK baru";
    }
    
    else if(cmb_status_kk.getSelectedItem().equals("Nomor KK tetap")){
        stts_kk_p="Nomor KK tetap";
    }
    
    nik_pemohon=txt_nik_mohon.getText();
    alamat_asal=txt_alamat.getText();
    rt_asal=txt_rt.getText();
    rw_asal=txt_rw.getText();
    desa_asal=txt_desa.getText();
    kec_asal=txt_kec.getText();
    kab_asal=txt_kab.getText();
    prov_asal=txt_prov.getText();
    kode_pos_asal=txt_kode_pos.getText();
    
    String tampil_tgl="yyyy-MM-dd";
    Calendar cal=dateChooserCombo1.getSelectedDate();
    SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
    tgl_datang=String.valueOf(format1.format(cal.getTime()));
    
    if(cmb_jenis_kedatangan.getSelectedItem().equals("Kepala keluarga")){
        jenis_pindah="1";
    }
    else if(cmb_jenis_kedatangan.getSelectedItem().equals("Kep. keluarga dan seluruh anggota")){
        jenis_pindah="2";
    }
    
    else if(cmb_jenis_kedatangan.getSelectedItem().equals("Kep. keluarga dan sebagian anggota")){
        jenis_pindah="3";
    }
    
    try{
    Statement state =(Statement)Koneksi.koneksi().createStatement();
        state.executeUpdate("UPDATE  data_pendatang  SET  no_kk='"+no_kk
        +"',"+" stt_kk_p='"+stts_kk_p
        +"',"+" nik_pemohon='"+nik_pemohon
        +"',"+" alamat_asal='"+alamat_asal
        +"',"+" rt_asal='"+rt_asal
        +"',"+" rw_asal='"+rw_asal
        +"',"+" desa_asal='"+desa_asal
        +"',"+" kecamatan_asal='"+kec_asal
        +"',"+" kab_asal='"+kab_asal
        +"',"+" prov_asal='"+prov_asal
        +"',"+" kode_pos_asal='"+kode_pos_asal
        +"',"+" tgl_datang='"+tgl_datang        
        +"' "+" where no_pendatang='"+no_datang+"';");

        state.close();
        JOptionPane.showMessageDialog(null, "Data telah diubah. . .");
        clean();
        
        } catch(Exception e){
         JOptionPane.showMessageDialog(null, "Data gagal diubah . . .");
        }
        
    
}
    private void cari(String kondisi1){
          try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                     
                    ResultSet rs = st.executeQuery("SELECT no_pendatang,no_kk,stt_kk_p,nik_pemohon,"
                    + "alamat_asal,rt_asal,rw_asal,desa_asal,kecamatan_asal,"
                    + "kab_asal,prov_asal,kode_pos_asal,tgl_datang,"
                    + "CASE WHEN jenis_kepindahan='1' THEN 'Kepala keluarga'"
                    + "WHEN jenis_kepindahan='2' THEN 'Kep. keluarga dan seluruh anggota'"
                    + "WHEN jenis_kepindahan='3' THEN 'Kep. keluarga dan sebagian anggota'"
                    + "WHEN jenis_kepindahan='4' THEN 'Anggota keluarga'"
                    + "END AS jenis_kedatangan FROM data_pendatang WHERE "+kondisi1+" like '%"+search+"%'");
                    
                   

                    tabelModel.setRowCount(0);
                    String [] data = new String[14];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] =rs.getString("no_pendatang");
                        data[1] =rs.getString("no_kk");
                        data[2] =rs.getString("stt_kk_p");
                        data[3] =rs.getString("nik_pemohon");
                        data[4] =rs.getString("alamat_asal");
                        data[5] =rs.getString("rt_asal");
                        data[6] =rs.getString("rw_asal");
                        data[7] =rs.getString("desa_asal");
                        data[8] =rs.getString("kecamatan_asal");
                        data[9] =rs.getString("kab_asal");
                        data[10] =rs.getString("prov_asal");
                        data[11] =rs.getString("kode_pos_asal");
                        data[12] =rs.getString("tgl_datang");
                        data[13] =rs.getString("jenis_kedatangan");
                        
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }  

    }
    
private void noTable(){
     no_datang=txt_datang_1.getText();
     int baris = tabelModel_keluarga_datang.getRowCount(); 
        for(int a=0; a<baris; a++){
           String nomor = String.valueOf(a+1);
           tabelModel_keluarga_datang.setValueAt(nomor + "", a, 0);
           tabelModel_keluarga_datang.setValueAt(no_datang + "", a, 1);
        }
      
}


private void tabelklik_penduduk(){
    int baris=tabel_cari_penduduk.getSelectedRow();
    if(txt_kk.getText().equals((String)tabel_cari_penduduk.getValueAt(baris, 1))){
                if(baris == -1){return;}

                nik_pemohon=(String)tabel_cari_penduduk.getValueAt(baris, 0);
                Object[] obj = new Object[3];
                obj[2] = nik_pemohon;
                String s="";
                boolean exist =false;

               for(int i=0;i<tabel_keluarga_datang.getRowCount();i++){
                   s=tabel_keluarga_datang.getValueAt(i, 2).toString().trim();
                   if(nik_pemohon.equals(s)){
                       exist=true;
                       break;
                   }
               }
                if(txt_datang_1.getText().equals("________________")){
                    JOptionPane.showMessageDialog(null,"Klik pilih pada tabel datang Penduduk dahulu");

                }
               else if(!exist){
                   tabelModel_keluarga_datang.addRow(obj);
                    noTable();
               }
               else{
                   JOptionPane.showMessageDialog(null,"data sudah ada");

               }
    }
    else{JOptionPane.showMessageDialog(null,"data yang dipilih memiliki no kk yang berbeda");}
}




private void simpan_keluarga_dtang(){
    int baris=tabel_keluarga_datang.getSelectedRow();
    String cek_nik="";
    if(baris == -1){return;}
    no_datang=tabel_keluarga_datang.getValueAt(baris, 1).toString();
    nik_pemohon=tabel_keluarga_datang.getValueAt(baris, 2).toString();
  
    
    
    try{
            Statement statement =(Statement)Koneksi.koneksi().createStatement();
            Statement state =(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("select nik from detail_pendatang where nik='"+nik_pemohon+"'");
            
            while (next_row.next()){
                   cek_nik=next_row.getString("nik");
            }

            if(cek_nik.equals(nik_pemohon)){
                JOptionPane.showMessageDialog(null,"data NIk sudah ada");

            }

            else{
            statement.executeUpdate("insert into detail_pendatang (no_pendatang,nik) values('"
                +no_datang+"','"    
                +nik_pemohon+"');");

            statement.close();
            JOptionPane.showMessageDialog(null,"Data Telah Disimpan....");
            tabel_keluarga_datang.setValueAt("",baris, 0);
            tabel_keluarga_datang.setValueAt("",baris, 1);
            tabel_keluarga_datang.setValueAt("",baris, 2);

            clean();
            }
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,""+e);
        }
    
}



int row=0;
private void tabelklik() throws ParseException{
    data_tabel_penduduk();
    lebarkolom2();
   row=tabel_datang.getSelectedRow();
    txt_datang.setText(tabel_datang.getValueAt(row, 0).toString());
    txt_datang_1.setText(tabel_datang.getValueAt(row, 0).toString());
    txt_kk.setText(tabel_datang.getValueAt(row, 1).toString());
    
    if(tabel_datang.getValueAt(row, 2).toString().equals("Numpang KK")){
        cmb_status_kk.setSelectedItem("Numpang KK");}
    else if(tabel_datang.getValueAt(row, 2).toString().equals("Membuat KK baru")){
        cmb_status_kk.setSelectedItem("Membuat KK baru");}
    else if(tabel_datang.getValueAt(row, 2).toString().equals("Nomor KK tetap")){
        cmb_status_kk.setSelectedItem("Nomor KK tetap");}
    
    txt_nik_mohon.setText(tabel_datang.getValueAt(row, 3).toString());
    txt_alamat.setText(tabel_datang.getValueAt(row, 4).toString());
    txt_rt.setText(tabel_datang.getValueAt(row, 5).toString());
    txt_rw.setText(tabel_datang.getValueAt(row, 6).toString());
    txt_desa.setText(tabel_datang.getValueAt(row, 7).toString());
    txt_kec.setText(tabel_datang.getValueAt(row, 8).toString());
    txt_kab.setText(tabel_datang.getValueAt(row, 9).toString());
    txt_prov.setText(tabel_datang.getValueAt(row, 10).toString());
    txt_kode_pos.setText(tabel_datang.getValueAt(row, 11).toString());
    
    tgl_datang = tabel_datang.getValueAt(row, 12).toString(); 
    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_datang);
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    dateChooserCombo1.setSelectedDate(cal);
    
    
    if(tabel_datang.getValueAt(row, 13).toString().equals("Kepala keluarga")){
        cmb_jenis_kedatangan.setSelectedItem("Kepala keluarga");
    }
    
    else if(tabel_datang.getValueAt(row, 13).toString().equals("Kep. keluarga dan seluruh anggota")){
        cmb_jenis_kedatangan.setSelectedItem("Kep. keluarga dan seluruh anggota");
    }
    
    
    else if(tabel_datang.getValueAt(row, 13).toString().equals("Kep. keluarga dan sebagian anggota")){
        cmb_jenis_kedatangan.setSelectedItem("Kep. keluarga dan sebagian anggota");
    }
    
    else if(tabel_datang.getValueAt(row, 13).toString().equals("Anggota keluarga")){
        cmb_jenis_kedatangan.setSelectedItem("Anggota keluarga");
    }
    
     
     
        
        
        
    jButton1.setText("save ");
    
    
    

}


  private void hapus (){
        
     no_datang = txt_datang.getText();
         try{
             Statement statement=(Statement)Koneksi.koneksi().createStatement();
             statement.executeUpdate("delete from data_pendatang where no_pendatang ='"+no_datang+"';");
             statement.close();
             JOptionPane.showMessageDialog(null,"data telah terhapus");
            
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"data gagal dihapus");
         }   
  }
  
  
  private void hapus_detail_pendatang (){
     int baris=tabel_keluarga_datang.getSelectedRow();
     no=(String)tabel_keluarga_datang.getValueAt(baris, 0);
     
     
     
            if(baris == -1){return;}
            no_datang = txt_datang.getText();

                try{
                    Statement statement=(Statement)Koneksi.koneksi().createStatement();
                    statement.executeUpdate("delete from detail_pendatang where no ='"+no+"';");
                    statement.close();
                    JOptionPane.showMessageDialog(null,"data telah terhapus");

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"data gagal dihapus");
                } 
     
  }
  
  public void autonumber() {
        try {
            Statement st =(Statement)Koneksi.koneksi().createStatement();
            String query_bukaTabel="select right(no_pendatang,5) as no_urut from data_pendatang GROUP BY no_pendatang ASC";
            java.sql.ResultSet line_result = st.executeQuery(query_bukaTabel);
            if (line_result.first() == false) {
                txt_datang.setText("1");
            } else {
                line_result.last();
                int no = line_result.getInt(1) + 1;
                
                String nomor = String.valueOf(no);
                int oto = nomor.length();
                    String x=nomor;
                txt_datang.setText(""+x);
            }
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }  
  
    
    
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari_kk = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jframe_transparant1 = new background.jframe_transparant();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_kk = new javax.swing.JTextField();
        txt_datang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_prov = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_nik_mohon = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_rt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_rw = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_desa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_kec = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_kab = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_kode_pos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cmb_jenis_kedatangan = new javax.swing.JComboBox();
        cmb_status_kk = new javax.swing.JComboBox();
        jButton13 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_datang = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmb_cari = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        clPanelTransparan3 = new PanelTransparan.ClPanelTransparan();
        cmb_cari1 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        txt_cari1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_cari_penduduk = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabel_keluarga_datang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txt_datang_1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txt_cari_kk.setBackground(new java.awt.Color(204, 204, 204));
        txt_cari_kk.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_cari_kk.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton6.setText("cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel25.setText("NIK/ Nama");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txt_cari_kk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1012, 574));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 566));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Datang Penduduk");

        clPanelTransparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16_2).png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16).png"))); // NOI18N
        jButton2.setText("clean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setText("No Pendatang");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Nik Pemohon");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Status KK Pindah");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Alamat Asal");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("No KK");

        txt_kk.setEditable(false);
        txt_kk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_kk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_kkMouseClicked(evt);
            }
        });

        txt_datang.setEditable(false);
        txt_datang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Provinsi asal");

        txt_prov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Jenis kedatangan");

        txt_nik_mohon.setEditable(false);
        txt_nik_mohon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nik_mohon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nik_mohonMouseClicked(evt);
            }
        });

        txt_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Rt asal");

        txt_rt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rtKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("Rw asal");

        txt_rw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rwKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText("Desa asal");

        txt_desa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setText("Kecamatan asal");

        txt_kec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setText("Kabupaten asal");

        txt_kab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText("Kode Pos asal");

        txt_kode_pos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_kode_pos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kode_posKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setText("Tanggal datang");

        cmb_jenis_kedatangan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_jenis_kedatangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Jenis Kedatangan--", "Kepala keluarga", "Kep. keluarga dan seluruh anggota", "Kep. keluarga dan sebagian anggota", "Anggota keluarga" }));

        cmb_status_kk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_status_kk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Status KK--", "Numpang KK", "Membuat KK baru", "Nomor KK tetap" }));

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_report.png"))); // NOI18N
        jButton13.setText("report");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        dateChooserCombo1.setNothingAllowed(false);
        dateChooserCombo1.setFormat(0);
        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        dateChooserCombo1.setLocale(new java.util.Locale("in", "ID", ""));

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13))
                                .addGap(53, 53, 53)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_desa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addComponent(txt_nik_mohon, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18)
                                        .addGap(29, 29, 29)
                                        .addComponent(txt_kode_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addComponent(txt_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                                .addComponent(txt_datang, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(jLabel19)))
                                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb_status_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(txt_kk))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmb_jenis_kedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kec, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kab, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_datang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nik_mohon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kode_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmb_status_kk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(cmb_jenis_kedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_rw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_rt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_desa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16))
                    .addComponent(txt_kec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_kab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(38, 38, 38)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton13))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        clPanelTransparan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tabel_datang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_datang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_datang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_datang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_datangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_datang);
        if (tabel_datang.getColumnModel().getColumnCount() > 0) {
            tabel_datang.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Cari");

        cmb_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Cari berdasar--", "No Pendatang", "Nik" }));
        cmb_cari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cariItemStateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton11.setText("Refresh");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(29, 29, 29)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        clPanelTransparan3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cmb_cari1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_cari1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Cari berdasar--", "Nama", "Nik", "No KK" }));
        cmb_cari1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cari1ItemStateChanged(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton5.setText("cari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_cari1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel23.setText("Cari");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Penduduk");

        tabel_cari_penduduk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_cari_penduduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_cari_penduduk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_cari_penduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_cari_pendudukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_cari_penduduk);
        if (tabel_cari_penduduk.getColumnModel().getColumnCount() > 0) {
            tabel_cari_penduduk.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        tabel_keluarga_datang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_keluarga_datang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_keluarga_datang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_keluarga_datang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_keluarga_datangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabel_keluarga_datang);
        if (tabel_keluarga_datang.getColumnModel().getColumnCount() > 0) {
            tabel_keluarga_datang.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Keluarga yang datang");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add.png"))); // NOI18N
        jButton8.setText("add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        jButton9.setText("delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("No Pendatang");

        txt_datang_1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_datang_1.setText("________________");

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16).png"))); // NOI18N
        jButton12.setText("clean");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan3Layout = new javax.swing.GroupLayout(clPanelTransparan3);
        clPanelTransparan3.setLayout(clPanelTransparan3Layout);
        clPanelTransparan3Layout.setHorizontalGroup(
            clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addComponent(jLabel2)
                            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_datang_1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        clPanelTransparan3Layout.setVerticalGroup(
            clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(clPanelTransparan3Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txt_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_cari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txt_datang_1))))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(clPanelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(clPanelTransparan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(txt_nik_mohon.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Klik dahulu pada tabel pendatang,pilih No pendatang yang dihapus","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
         String[] Opsi={"YA","TIDAK"};
        int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Ingin Menghapus Data ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih==JOptionPane.YES_OPTION){
        hapus();
        clean();
        data_tabel();
        lebarKolom();
        
        } else if(Pilih==JOptionPane.NO_OPTION){
              data_tabel();
              lebarKolom(); 
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txt_datang.getText().equals("")||txt_nik_mohon.getText().equals("")||cmb_jenis_kedatangan.getSelectedItem().equals("--Jenis Kedatangan--")
        ||txt_kk.getText().equals("")||txt_alamat.getText().equals("")||txt_rt.getText().equals("")||txt_rw.getText().equals("")
        ||txt_desa.getText().equals("")||txt_kec.getText().equals("")||txt_kab.getText().equals("")||txt_prov.getText().equals("")
        ||txt_kode_pos.getText().equals("")||cmb_status_kk.getSelectedItem().equals("--Status KK--")){
            
            JOptionPane.showMessageDialog(null,"Filed belum dilengkapi");
        }
        
        else{
                if(jButton1.getText().equals("save")){
                    if(txt_kode_pos.getText().length()<5){JOptionPane.showMessageDialog(null,"Kode pos kurang dari 5 digit");}
                    else{
                        simpan();
                        data_tabel();
                        lebarKolom();
                    }
                }

                else if(jButton1.getText().equals("save ")){
                    String[] Opsi={"YA","TIDAK"};
                    int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Mengubah Data Ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
                    if(Pilih==JOptionPane.YES_OPTION){
                    update();
                    clean();
                    data_tabel();
                    lebarKolom();
                    } else if(Pilih==JOptionPane.NO_OPTION)
                           data_tabel();
                           lebarKolom(); 

                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String nik1;
        int bantu=0;
        no_kk = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
       
         
         nik_pemohon = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
         
         ResultSet rs;
         try{
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM data_pendatang where nik_pemohon='"+nik_pemohon+"'");
              nik1=null;
            while (rs.next()){
               nik1=rs.getString("nik_pemohon");
               if(nik_pemohon.equals(nik1)){bantu=1;}
            }
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
         
         if(bantu==1){JOptionPane.showMessageDialog(null,"NIK sudah ada pada data kelahiran");}
         
         else if(bantu!=1){
             txt_nik_mohon.setText(nik_pemohon);
              txt_kk.setText(no_kk);
             jDialog1.setVisible(false);
             
         }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(txt_cari_kk.getText().equals("")){JOptionPane.showMessageDialog(null,"Field masih kosong");}
        
        else{
            try
            {
                Statement st = (Statement)Koneksi.koneksi().createStatement();
                String search = txt_cari_kk.getText();
                ResultSet rs = st.executeQuery("SELECT * FROM penduduk WHERE stts='kosong' and nik like '%"+search+"%' OR nama like '%"+search+"%'");
               // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                tabelModel_dialog.setRowCount(0);
                String [] data = new String[3];
                int i = 1;

                while(rs.next())
                {
                    data[0] = rs.getString("nik");
                    data[1] = rs.getString("no_kk");
                    data[2]=rs.getString("nama");

                    tabelModel_dialog.addRow(data);
                    i++;
                }
                rs.close();
                //txtcari.setText("");
            }
            catch(Exception ex)  {
                JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                System.err.println("error (search) : " +ex);
            }
        }
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         txt_cari_kk.setText("");
         data_tabel_jdialog();
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_datangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_datangMouseClicked
        // TODO add your handling code here:
       if(evt.getClickCount()==1){
           try {
               
               tabelklik();
               lebarKolom();
               
               data_tabel_datang1();
               lebarkolom3();
               
               
               
           } catch (ParseException ex) {
               Logger.getLogger(data_datang.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_tabel_datangMouseClicked

    private void cmb_cariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cariItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_cariItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(cmb_cari.getSelectedItem().equals("No Pendatang")){cari("no_pendatang");lebarKolom();}
        
        else if(cmb_cari.getSelectedItem().equals("Nik")){cari("nik_pemohon");lebarKolom();}
        
        else{JOptionPane.showMessageDialog(null,"Pilih filter pencarian dahulu");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmb_cari1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cari1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_cari1ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(cmb_cari1.getSelectedItem().equals("Nama")){
                cari_penduduk("nama");
        }
        
        else if(cmb_cari1.getSelectedItem().equals("Nik")){
                cari_penduduk("nik");
        }
        
        else if(cmb_cari1.getSelectedItem().equals("No KK")){
                cari_penduduk("no_kk");
        }
        else{JOptionPane.showMessageDialog(null,"Pilih filter pencarian dahulu");}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabel_cari_pendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_cari_pendudukMouseClicked
        // TODO add your handling code here:
        tabelklik_penduduk();
    }//GEN-LAST:event_tabel_cari_pendudukMouseClicked

    private void tabel_keluarga_datangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_keluarga_datangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_keluarga_datangMouseClicked

    private void txt_nik_mohonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nik_mohonMouseClicked
        // TODO add your handling code here:
        jDialog1.setLocationRelativeTo(frame);
        jDialog1.setBounds(0,0,472,280);
        data_tabel_jdialog();
        jDialog1.setVisible(true);
      
    }//GEN-LAST:event_txt_nik_mohonMouseClicked

    private void txt_kkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_kkMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_kkMouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        data_tabel();
        txt_cari.setText("");
        cmb_cari.setSelectedIndex(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         int baris=tabel_keluarga_datang.getSelectedRow();
         if(baris == -1){JOptionPane.showMessageDialog(null,"data yang akan ditambahkan belum ada atau data yang akan ditambahkan belum dipiih");return;}
        simpan_keluarga_dtang();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        int baris=tabel_keluarga_datang.getSelectedRow();
         if(baris == -1){JOptionPane.showMessageDialog(null,"Klik pilih pada tabel pendatang  dahulu \n Kemudian  klik pilih tabel keluarga pendatang \n Klik pilih yang akan dihapus");return;}
     
     else{  
         String[] Opsi={"YA","TIDAK"};
        int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Ingin Menghapus Data ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih==JOptionPane.YES_OPTION){
        hapus_detail_pendatang();
        clean();
        data_tabel_datang1();
        lebarkolom3();
        } else if(Pilih==JOptionPane.NO_OPTION){
                data_tabel_datang1();
                lebarkolom3();
        }
              
                                 
     }    
        
         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         data_tabel_datang2();
        lebarkolom3();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        txt_cari1.setText("");
        cmb_cari1.setSelectedIndex(0);
        data_tabel_penduduk();
        lebarkolom2();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Laporan_data_datang baru=new Laporan_data_datang();
        baru.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void txt_rtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rtKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
        else if(txt_rt.getText().length()==3){evt.consume();}
    }//GEN-LAST:event_txt_rtKeyTyped

    private void txt_rwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rwKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
        else if(txt_rw.getText().length()==3){evt.consume();}
    }//GEN-LAST:event_txt_rwKeyTyped

    private void txt_kode_posKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kode_posKeyTyped
        // TODO add your handling code here:
          char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
        else if(txt_kode_pos.getText().length()==5){evt.consume();}
    }//GEN-LAST:event_txt_kode_posKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private PanelTransparan.ClPanelTransparan clPanelTransparan3;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JComboBox cmb_cari1;
    private javax.swing.JComboBox cmb_jenis_kedatangan;
    private javax.swing.JComboBox cmb_status_kk;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private background.jframe_transparant jframe_transparant1;
    private javax.swing.JTable tabel_cari_penduduk;
    private javax.swing.JTable tabel_datang;
    private javax.swing.JTable tabel_keluarga_datang;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_cari1;
    private javax.swing.JTextField txt_cari_kk;
    private javax.swing.JTextField txt_datang;
    private javax.swing.JLabel txt_datang_1;
    private javax.swing.JTextField txt_desa;
    private javax.swing.JTextField txt_kab;
    private javax.swing.JTextField txt_kec;
    private javax.swing.JTextField txt_kk;
    private javax.swing.JTextField txt_kode_pos;
    private javax.swing.JTextField txt_nik_mohon;
    private javax.swing.JTextField txt_prov;
    private javax.swing.JTextField txt_rt;
    private javax.swing.JTextField txt_rw;
    // End of variables declaration//GEN-END:variables
        }
