package Form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hades
 */
import background.autoresize_tabel;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;
public class data_kelahiran extends javax.swing.JInternalFrame {

    /**
     * Creates new form penduduk
     */
    public data_kelahiran()   {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        autonumber();
        data_tabel();
       lebarKolom();
      
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private String no_lahir,nik,no_kk,nama_lapor, tempat_lahir,kota_lahir, tgl_lahir, pukul, jenis_lahir,tolong_lahir,ibu,ayah,nik_lapor;
      private double b_bayi,p_bayi;
      
      private home frame= new home();
      
      private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"No Kelahiran","NIK","No KK","Tempat Lahir","Kota Lahir","Tanggal Lahir","Waktu Lahir","Jenis Lahir","Penolong","Berat Bayi","Panjang Bayi","Ibu","Ayah","NIK Pelapor","Nama Pelapor"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,false,false,false,false,false,false,false,false,false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
                
    
    private javax.swing.table.DefaultTableModel tabelModel=getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel tabelModel_dialog=getDefaultTabelModel();
    
    
    private void lebarKolom() {
        TableColumn lebar_kolom;

        

        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(0);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(1);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(3);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(4);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(5);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(6);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(7);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(8);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(9);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(10);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(11);
        lebar_kolom.setPreferredWidth(100);
         lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(12);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(13);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_kelahiran.getColumnModel().getColumn(14);
        lebar_kolom.setPreferredWidth(100);



        
        lebar_kolom.setPreferredWidth(100);


        

    }   
    
private void data_tabel(){
tabel_kelahiran.setAutoResizeMode(tabel_kelahiran.AUTO_RESIZE_OFF);    
tabel_kelahiran.setModel(tabelModel);
try{
Statement state=(Statement)Koneksi.koneksi().createStatement();
ResultSet res=state.executeQuery("select*from data_kelahiran GROUP BY no_kelahiran");
String[] colom={"No Kelahiran","NIK","No KK","Tempat Lahir","Kota Lahir","Tanggal Lahir","Waktu Lahir","Jenis Lahir","Penolong","Berat Bayi","Panjang Bayi","Ibu","Ayah","NIK Pelapor","Nama Pelapor"};
tabelModel.setDataVector(null,colom);
while(res.next())
{
tabelModel.addRow(new Object[]{
res.getString("no_kelahiran"),
res.getString("nik"),
res.getString("no_kk"),
res.getString("tempat_lahir"),
res.getString("kota_lahir"),
res.getString("tgl_lahir"),
res.getString("pukul"),
res.getString("jenis_kelahiran"),
res.getString("penolong_kelahiran"),
res.getString("b_bayi"),
res.getString("p_bayi"),
res.getString("nama_ibu"),
res.getString("nama_ayah"),
res.getString("nik_pelapor"),
res.getString("nama_pelapor"),
});

}
}catch (Exception e){
JOptionPane.showMessageDialog(rootPane,""+e);
}
new autoresize_tabel().Kolom(tabel_kelahiran);
tabel_kelahiran.revalidate(); 
}

public void data_tabel_jdialog(){
        jTable1.setModel(tabelModel_dialog);
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("select * from penduduk where stts='kosong'");
            String [] kolom={"NIK","No KK","Nama"};
            tabelModel_dialog.setDataVector(null, kolom);
            
             while(next_row.next()){
                 tabelModel_dialog.addRow(new Object[] {
                 next_row.getString("nik"),
                 next_row.getString("no_kk"),    
                 next_row.getString("nama"),
                 
                 
                 });
             }
             
        }catch(Exception e){
    
        }
    }
    
    
    private void simpan(){
        no_lahir=txt_id.getText();
        nik=txt_nik.getText();
        no_kk=txt_kk.getText();
        if(cmb_tempat_lahir.getSelectedItem().equals("Rumah sakit")){tempat_lahir="Rumah sakit";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Rumah bersalin")){tempat_lahir="Rumah bersalin";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Puskesmas")){tempat_lahir="Puskesmas";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Polindes")){tempat_lahir="Polindes";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Rumah")){tempat_lahir="Rumah";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Lainnya")){tempat_lahir="Lainnya";}
        kota_lahir=txt_kota_lahir.getText();
        
        
        
        String tampil_tgl="yyyy-MM-dd";
        Calendar cal=dateChooserCombo1.getSelectedDate();
        SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
        tgl_lahir=String.valueOf(format1.format(cal.getTime()));
        
        String tampil_jam="HH:mm:ss";
        SimpleDateFormat format2=new SimpleDateFormat(tampil_jam);
        pukul=String.valueOf(format2.format(spin_time.getValue()));
        
        
        if(cmb_jenis_lahir.getSelectedItem().equals("Tunggal")){jenis_lahir="Tunggal";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 2")){jenis_lahir="Kembar 2";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 3")){jenis_lahir="Kembar 3";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 4")){jenis_lahir="Kembar 4";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Lainnya")){jenis_lahir="Lainnya";}
        
        if(cmb_tolong_lahir.getSelectedItem().equals("Dokter")){tolong_lahir="Dokter";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Bidan")){tolong_lahir="Bidan";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Perawat")){tolong_lahir="Perawat";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Dukun")){tolong_lahir="Dukun";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Lainnya")){tolong_lahir="Lainnya";}
        
        b_bayi=Double.valueOf(txt_berat.getText());
        p_bayi=Double.valueOf(txt_panjang.getText());
        ibu=txt_ibu.getText();
        ayah=txt_ayah.getText();
        nik_lapor=txt_nik_lapor.getText();
        nama_lapor=txt_nama_lapor.getText();
        
        
        
        
    try{
        Statement statement =(Statement)Koneksi.koneksi().createStatement();
        statement.executeUpdate("insert into data_kelahiran values('"
            +no_lahir+"','"
            +nik+"','"
            +no_kk+"','"
            +tempat_lahir+"','"
            +kota_lahir+"','"
            +tgl_lahir+"','"
            +pukul+"','"
            +jenis_lahir+"','"
            +tolong_lahir+"','"
            +b_bayi+"','"
            +p_bayi+"','"
            +ibu+"','"
            +ayah+"','"
            +nik_lapor+"','"    
            +nama_lapor+"');");

        statement.close();
        JOptionPane.showMessageDialog(null,"Data Telah Disimpan....");
        clean();
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,""+e);
        }
              
  
    }
    
    private void clean(){
        
        txt_id.setText("");
        autonumber();
        txt_nik.setText("");
        txt_kk.setText("");
        txt_kota_lahir.setText("");
        cmb_tempat_lahir.setSelectedItem("--tempat dilahirkan--");
        cmb_jenis_lahir.setSelectedItem("--Jenis Kelahiran--");
        cmb_tolong_lahir.setSelectedItem("--Penolong Kelahiran--");
        txt_berat.setText("");
        txt_panjang.setText("");
        txt_ibu.setText("");
        txt_ayah.setText("");
        
        
        txt_nama_lapor.setText("");
        txt_nik_lapor.setText("");
        jButton1.setText("save");
    
    }
    
    
private void update(){
    no_lahir=txt_id.getText();
        nik=txt_nik.getText();
        no_kk=txt_kk.getText();
        if(cmb_tempat_lahir.getSelectedItem().equals("Rumah sakit")){tempat_lahir="Rumah sakit";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Rumah bersalin")){tempat_lahir="Rumah bersalin";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Puskesmas")){tempat_lahir="Puskesmas";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Polindes")){tempat_lahir="Polindes";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Rumah")){tempat_lahir="Rumah";}
        else if(cmb_tempat_lahir.getSelectedItem().equals("Lainnya")){tempat_lahir="Lainnya";}
        kota_lahir=txt_kota_lahir.getText();
        
        String tampil_tgl="yyyy-MM-dd";
        Calendar cal=dateChooserCombo1.getSelectedDate();
        SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
        tgl_lahir=String.valueOf(format1.format(cal.getTime()));
        
        String tampil_jam="HH:mm:ss";
        SimpleDateFormat format2=new SimpleDateFormat(tampil_jam);
        pukul=String.valueOf(format2.format(spin_time.getValue()));
        
        
        if(cmb_jenis_lahir.getSelectedItem().equals("Tunggal")){jenis_lahir="Tunggal";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 2")){jenis_lahir="Kembar 2";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 3")){jenis_lahir="Kembar 3";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Kembar 4")){jenis_lahir="Kembar 4";}
        else if(cmb_jenis_lahir.getSelectedItem().equals("Lainnya")){jenis_lahir="Lainnya";}
        
        if(cmb_tolong_lahir.getSelectedItem().equals("Dokter")){tolong_lahir="Dokter";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Bidan")){tolong_lahir="Bidan";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Perawat")){tolong_lahir="Perawat";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Dukun")){tolong_lahir="Dukun";}
        else if(cmb_tolong_lahir.getSelectedItem().equals("Lainnya")){tolong_lahir="Lainnya";}
        
        b_bayi=Double.valueOf(txt_berat.getText());
        p_bayi=Double.valueOf(txt_panjang.getText());
        ibu=txt_ibu.getText();
        ayah=txt_ayah.getText();
        nik_lapor=txt_nik_lapor.getText();
        nama_lapor=txt_nama_lapor.getText();
        
         try{

        Statement state =(Statement)Koneksi.koneksi().createStatement();
        state.executeUpdate("UPDATE  data_kelahiran  SET  nik='"+nik
        +"',"+" no_kk='"+no_kk
        +"',"+" tempat_lahir='"+tempat_lahir
        +"',"+" kota_lahir='"+kota_lahir
        +"',"+" tgl_lahir='"+tgl_lahir
        +"',"+" pukul='"+pukul
        +"',"+" jenis_kelahiran='"+jenis_lahir
        +"',"+" penolong_kelahiran='"+tolong_lahir
        +"',"+" b_bayi='"+b_bayi
        +"',"+" p_bayi='"+p_bayi
        +"',"+" nama_ibu='"+ibu
        +"',"+" nama_ayah='"+ayah
        +"',"+" nik_pelapor='"+nik_lapor
        +"',"+" nama_pelapor='"+nama_lapor        
        +"' "+" where no_kelahiran='"+no_lahir+"';");

        state.close();
        JOptionPane.showMessageDialog(null, "Data telah di Ubah. . .");
        clean();
        } catch(Exception e){
         JOptionPane.showMessageDialog(null, "data gagal di Ubah . . .");
        }
        
    
}

int row=0;
private void tabelklik() throws ParseException{
    row=tabel_kelahiran.getSelectedRow();
    txt_id.setText(tabel_kelahiran.getValueAt(row, 0).toString());
    txt_nik.setText(tabel_kelahiran.getValueAt(row, 1).toString());
    txt_kk.setText(tabel_kelahiran.getValueAt(row, 2).toString());
    
    if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Rumah sakit")){
        cmb_tempat_lahir.setSelectedItem("Rumah sakit");}    
    else if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Rumah bersalin")){
        cmb_tempat_lahir.setSelectedItem("Rumah bersalin");}
    else if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Puskesmas")){
        cmb_tempat_lahir.setSelectedItem("Puskesmas");}
    else if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Polindes")){
        cmb_tempat_lahir.setSelectedItem("Polindes");}
    else if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Rumah")){
        cmb_tempat_lahir.setSelectedItem("Rumah");}
    else if(tabel_kelahiran.getValueAt(row, 3).toString().equals("Lainnya")){
        cmb_tempat_lahir.setSelectedItem("Lainnya");}
    
    txt_kota_lahir.setText(tabel_kelahiran.getValueAt(row, 4).toString());
    
    tgl_lahir = tabel_kelahiran.getValueAt(row, 5).toString(); 
    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tgl_lahir);
    Calendar cal = Calendar.getInstance();
    cal.setTime(date);
    dateChooserCombo1.setSelectedDate(cal);
    
    pukul = tabel_kelahiran.getValueAt(row, 6).toString();
    SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
    spin_time.setValue(time.parseObject(pukul));
    
    if(tabel_kelahiran.getValueAt(row, 7).toString().equals("Tunggal")){
    cmb_jenis_lahir.setSelectedItem("Tunggal");}
    else if(tabel_kelahiran.getValueAt(row, 7).toString().equals("Kembar 2")){
    cmb_jenis_lahir.setSelectedItem("Kembar 2");}
    else if(tabel_kelahiran.getValueAt(row, 7).toString().equals("Kembar 3")){
    cmb_jenis_lahir.setSelectedItem("Kembar 3");}
    else if(tabel_kelahiran.getValueAt(row, 7).toString().equals("Kembar 4")){
    cmb_jenis_lahir.setSelectedItem("Kembar 4");}
    else if(tabel_kelahiran.getValueAt(row, 7).toString().equals("Lainnya")){
    cmb_jenis_lahir.setSelectedItem("Lainnya");}
    
    
    if(tabel_kelahiran.getValueAt(row, 8).toString().equals("Dokter")){
    cmb_tolong_lahir.setSelectedItem("Dokter");}
    else if(tabel_kelahiran.getValueAt(row, 8).toString().equals("Bidan")){
    cmb_tolong_lahir.setSelectedItem("Bidan");}
    else if(tabel_kelahiran.getValueAt(row, 8).toString().equals("Perawat")){
    cmb_tolong_lahir.setSelectedItem("Perawat");}
    else if(tabel_kelahiran.getValueAt(row, 8).toString().equals("Dukun")){
    cmb_tolong_lahir.setSelectedItem("Dukun");}
    else if(tabel_kelahiran.getValueAt(row, 8).toString().equals("Lainnya")){
    cmb_tolong_lahir.setSelectedItem("Lainnya");}
    
    
    txt_berat.setText(tabel_kelahiran.getValueAt(row, 9).toString());
    txt_panjang.setText(tabel_kelahiran.getValueAt(row, 10).toString());
    txt_ibu.setText(tabel_kelahiran.getValueAt(row, 11).toString());
    txt_ayah.setText(tabel_kelahiran.getValueAt(row, 12).toString());
    txt_nik_lapor.setText(tabel_kelahiran.getValueAt(row, 13).toString());
    txt_nama_lapor.setText(tabel_kelahiran.getValueAt(row, 14).toString());
    
    jButton1.setText("save ");

}


  private void hapus (){
      no_lahir = txt_id.getText();
         try{
             Statement statement=(Statement)Koneksi.koneksi().createStatement();
             statement.executeUpdate("delete from data_kelahiran where no_kelahiran='"+no_lahir+"';");
             statement.close();
             JOptionPane.showMessageDialog(null,"data telah terhapus");
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"data gagal dihapus");
         }
        
  }
  
public void autonumber() {
        try {
            Statement st =(Statement)Koneksi.koneksi().createStatement();
            String query_bukaTabel="select right(no_kelahiran,5) as no_urut from data_kelahiran GROUP BY no_kelahiran ASC";
            java.sql.ResultSet line_result = st.executeQuery(query_bukaTabel);
            if (line_result.first() == false) {
                txt_id.setText("0");
            } else {
                line_result.last();
                int no = line_result.getInt(1) + 1;
                
                String nomor = String.valueOf(no);
                int oto = nomor.length();
                    String x=nomor;
                txt_id.setText(""+x);
            }
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }
  
    
    
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari_nik = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ayah = new javax.swing.JTextField();
        txt_ibu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nik_lapor = new javax.swing.JTextField();
        cmb_tempat_lahir = new javax.swing.JComboBox();
        txt_kk = new javax.swing.JTextField();
        txt_kota_lahir = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmb_jenis_lahir = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spin_time = new javax.swing.JSpinner();
        cmb_tolong_lahir = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txt_berat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_panjang = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_nama_lapor = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_kelahiran = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmb_cari = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txt_cari_nik.setBackground(new java.awt.Color(204, 204, 204));
        txt_cari_nik.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_cari_nik.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton6.setText("cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel25.setText("Nik/Nama");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txt_cari_nik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1012, 574));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 566));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Kelahiran");

        clPanelTransparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16_2).png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16).png"))); // NOI18N
        jButton2.setText("clean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setText("No Kelahiran");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("No KK");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Tempat Lahir");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Kota Lahir");

        txt_nik.setEditable(false);
        txt_nik.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nik.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txt_nikComponentAdded(evt);
            }
        });
        txt_nik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nikMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nikMousePressed(evt);
            }
        });
        txt_nik.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_nikInputMethodTextChanged(evt);
            }
        });
        txt_nik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nikKeyReleased(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Tempat Kelahiran");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Ayah");

        txt_ayah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_ibu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Ibu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Nik Pelapor");

        txt_nik_lapor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nik_lapor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nik_laporKeyTyped(evt);
            }
        });

        cmb_tempat_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_tempat_lahir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--tempat dilahirkan--", "Rumah sakit", "Rumah bersalin", "Puskesmas", "Polindes", "Rumah", "Lainnya" }));

        txt_kk.setEditable(false);
        txt_kk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_kota_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Jenis Kelahiran");

        cmb_jenis_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_jenis_lahir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Jenis Kelahiran--", "Tunggal", "Kembar 2", "Kembar 3", "Kembar 4", "Lainnya" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("Tanggal Lahir");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText("Waktu Lahir");

        spin_time.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.HOUR_OF_DAY));
        spin_time.setEditor(new javax.swing.JSpinner.DateEditor(spin_time, "HH:mm:ss"));

        cmb_tolong_lahir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_tolong_lahir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Penolong Kelahiran--", "Dokter", "Bidan", "Perawat", "Dukun", "Lainnya" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel16.setText("Berat Bayi");

        txt_berat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_beratKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel17.setText("Panjang Bayi");

        txt_panjang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_panjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_panjangKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel18.setText("Nama Pelapor");

        txt_nama_lapor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_report.png"))); // NOI18N
        jButton5.setText("report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel19.setText("kg");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel20.setText("cm");

        dateChooserCombo1.setNothingAllowed(false);
        dateChooserCombo1.setFormat(0);
        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        dateChooserCombo1.setLocale(new java.util.Locale("in", "ID", ""));

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel26)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(16, 16, 16)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(txt_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_kota_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(spin_time, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_tempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel18))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_jenis_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tolong_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(txt_panjang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addComponent(txt_ayah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ibu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nik_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nama_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_jenis_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_kota_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(spin_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)
                                    .addComponent(jButton5))
                                .addContainerGap())))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cmb_tolong_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txt_panjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_ayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_ibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_nik_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txt_nama_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))))
        );

        clPanelTransparan2.setForeground(new java.awt.Color(255, 255, 255));

        tabel_kelahiran.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_kelahiran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_kelahiran.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_kelahiran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kelahiranMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_kelahiran);
        if (tabel_kelahiran.getColumnModel().getColumnCount() > 0) {
            tabel_kelahiran.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Cari");

        cmb_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Cari berdasar--", "No kelahiran", "Nik" }));
        cmb_cari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cariItemStateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1086, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(29, 29, 29)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(txt_nik.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Klik dahulu pada tabel kelahiran,pilih No kelahiran yang dihapus","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
         String[] Opsi={"YA","TIDAK"};
        int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Ingin Menghapus Data ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih==JOptionPane.YES_OPTION){
        hapus();
        clean();
        data_tabel();
        lebarKolom();
        
        } else if(Pilih==JOptionPane.NO_OPTION){
              data_tabel();
              lebarKolom();  
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText().equals("")||txt_kk.getText().equals("")||txt_nik.getText().equals("")
          ||cmb_tempat_lahir.getSelectedItem().equals("--tempat dilahirkan--")||txt_kota_lahir.getText().equals("")
          ||cmb_jenis_lahir.getSelectedItem().equals("--Jenis Kelahiran--")
          ||txt_berat.getText().equals("")||txt_panjang.getText().equals("")||txt_ayah.getText().equals("")||txt_ibu.getText().equals("")
          ||txt_nik_lapor.getText().equals("")||txt_nama_lapor.getText().equals("")){
            
            JOptionPane.showMessageDialog(null,"Filed belum dilengkapi");
        
        }
        else{
                if(jButton1.getText().equals("save")){
                    if(txt_nik_lapor.getText().length()<16){JOptionPane.showMessageDialog(null,"NIK kurang dari 16 digit");}    
                    
                    else{
                        simpan();
                        data_tabel();
                        lebarKolom();
                    }
                }

                else if(jButton1.getText().equals("save ")){
                    String[] Opsi={"YA","TIDAK"};
                    int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Mengubah Data Ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
                    if(Pilih==JOptionPane.YES_OPTION){
                    update();
                    clean();
                    data_tabel();
                    lebarKolom();
                    } else if(Pilih==JOptionPane.NO_OPTION)
                           data_tabel();
                           lebarKolom(); 

                }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String nik1;
        int bantu=0;
          nik = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
          no_kk = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
           ResultSet rs;
         try{
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM data_kelahiran where nik='"+nik+"'");
              nik1=null;
            while (rs.next()){
               nik1=rs.getString("nik");
               if(nik.equals(nik1)){bantu=1;}
            }
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
         
         if(bantu==1){JOptionPane.showMessageDialog(null,"NIK sudah ada pada data kelahiran");}
         
         else if(bantu!=1){
             txt_nik.setText(nik);
             txt_kk.setText(no_kk);
             jDialog1.setVisible(false);
         }
                
         
                   
                   
               
         

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
      
            if(txt_cari_nik.getText().equals("")){JOptionPane.showMessageDialog(null,"Field masih kosong");}
            
            else{
              try
            {
                Statement st = (Statement)Koneksi.koneksi().createStatement();
                String search = txt_cari_nik.getText();    
                ResultSet rs = st.executeQuery("SELECT * FROM penduduk WHERE nik like '%"+search+"%' OR nama like '%"+search+"%' AND stts='kosong'");
                // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                tabelModel_dialog.setRowCount(0);
                String [] data = new String[3];
                int i = 1;

            while(rs.next())
            {
                data[0] = rs.getString("nik");
                data[1] = rs.getString("no_kk");
                data[2] = rs.getString("nama");
                
                tabelModel_dialog.addRow(data);
                i++;
            }
            rs.close();
            //txtcari.setText("");
        }
        catch(Exception ex)  {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }
    }
        
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         txt_cari_nik.setText("");
         data_tabel_jdialog();
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_kelahiranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kelahiranMouseClicked
        // TODO add your handling code here:
       if(evt.getClickCount()==1){
           try {
               tabelklik();
           } catch (ParseException ex) {
               Logger.getLogger(data_kelahiran.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_tabel_kelahiranMouseClicked

    private void cmb_cariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cariItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_cariItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(cmb_cari.getSelectedItem().equals("No kelahiran")){
           
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                     
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kelahiran WHERE no_kelahiran like '%"+search+"%'");
                   // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                    tabelModel.setRowCount(0);
                    String [] data = new String[15];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("no_kelahiran");
                        data[1] = rs.getString("nik");
                        data[2] = rs.getString("no_kk");
                        data[3] = rs.getString("tempat_lahir");
                        data[4] = rs.getString("kota_lahir");
                        data[5] = rs.getString("tgl_lahir");
                        data[6] = rs.getString("pukul");
                        data[7] = rs.getString("jenis_kelahiran");
                        data[8] = rs.getString("penolong_kelahiran");
                        data[9] = rs.getString("b_bayi");
                        data[10] = rs.getString("p_bayi");
                        data[11] = rs.getString("nama_ibu");
                        data[12] = rs.getString("nama_ayah");
                        data[13] = rs.getString("nik_pelapor");
                        data[14] = rs.getString("nama_pelapor");
                        
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        
        
        else if(cmb_cari.getSelectedItem().equals("Nik")){
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kelahiran WHERE nik like '%"+search+"%'");
                   // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                    tabelModel.setRowCount(0);
                    String [] data = new String[15];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("no_kelahiran");
                        data[1] = rs.getString("nik");
                        data[2] = rs.getString("no_kk");
                        data[3] = rs.getString("tempat_lahir");
                        data[4] = rs.getString("kota_lahir");
                        data[5] = rs.getString("tgl_lahir");
                        data[6] = rs.getString("pukul");
                        data[7] = rs.getString("jenis_kelahiran");
                        data[8] = rs.getString("penolong_kelahiran");
                        data[9] = rs.getString("b_bayi");
                        data[10] = rs.getString("p_bayi");
                        data[11] = rs.getString("nama_ibu");
                        data[12] = rs.getString("nama_ayah");
                        data[13] = rs.getString("nik_pelapor");
                        data[14] = rs.getString("nama_pelapor");
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        else{JOptionPane.showMessageDialog(null,"Pilih filter pencarian dahulu");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nikMouseClicked
        // TODO add your handling code here:
        jDialog1.setLocationRelativeTo(frame);
        jDialog1.setBounds(0,0,472,280);
        data_tabel_jdialog();
        jDialog1.setVisible(true);
        
        
       
    }//GEN-LAST:event_txt_nikMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         
         data_tabel();
         lebarKolom();
         txt_cari.setText("");
         cmb_cari.setSelectedItem("--Cari berdasar--");
         
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Laporan_data_kelahiran baru= new Laporan_data_kelahiran();
        baru.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idKeyTyped

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_nikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nikKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_nikKeyReleased

    private void txt_nikInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_nikInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_nikInputMethodTextChanged

    private void txt_nikComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txt_nikComponentAdded
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_txt_nikComponentAdded

    private void txt_nikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nikMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_nikMousePressed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_beratKeyReleased

    private void txt_beratKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)||(karakter == '.')))){
        getToolkit().beep();
        evt.consume();
    }
    
    }//GEN-LAST:event_txt_beratKeyTyped

    private void txt_panjangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_panjangKeyTyped
        // TODO add your handling code here:
             char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)||(karakter == '.')))){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_txt_panjangKeyTyped

    private void txt_nik_laporKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nik_laporKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_nik_lapor.getText().length()==16){evt.consume();}
    }//GEN-LAST:event_txt_nik_laporKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JComboBox cmb_jenis_lahir;
    private javax.swing.JComboBox cmb_tempat_lahir;
    private javax.swing.JComboBox cmb_tolong_lahir;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spin_time;
    private javax.swing.JTable tabel_kelahiran;
    private javax.swing.JTextField txt_ayah;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_cari_nik;
    private javax.swing.JTextField txt_ibu;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kk;
    private javax.swing.JTextField txt_kota_lahir;
    private javax.swing.JTextField txt_nama_lapor;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_nik_lapor;
    private javax.swing.JTextField txt_panjang;
    // End of variables declaration//GEN-END:variables
        }
