package Form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hades
 */
import background.autoresize_tabel;
import koneksi.Koneksi.*;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;
public class data_kematian extends javax.swing.JInternalFrame {

    /**
     * Creates new form penduduk
     */
    home baru=new home();
    public data_kematian()   {
        initComponents();
        autonumber();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        
        data_tabel();
        lebarKolom();
      
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private String id_mati,nik,tgl,jam,sebab,tempat,ket,ayah,ibu,nik_lapor,bantu1,nama_lapor;
      
      private home frame= new home();
      
      private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"Id Kematian","NIK","Tanggal Kematian","Pukul","Sebab","Tempat","Info","Ayah","Ibu","Nik Pelapor","Nama Pelapor"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,false,false,false,false,false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
                
    
    private javax.swing.table.DefaultTableModel tabelModel=getDefaultTabelModel();
    private javax.swing.table.DefaultTableModel tabelModel_dialog=getDefaultTabelModel();
    
    
    private void lebarKolom() {
        TableColumn lebar_kolom;

        

        lebar_kolom = tabel_kematian.getColumnModel().getColumn(0);
        lebar_kolom.setPreferredWidth(80);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(3);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(4);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(5);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(6);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(7);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(8);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(9);
        lebar_kolom.setPreferredWidth(150);
        lebar_kolom = tabel_kematian.getColumnModel().getColumn(10);
        lebar_kolom.setPreferredWidth(150);
        
        lebar_kolom.setPreferredWidth(100);


        

    }   
    
private void data_tabel(){
tabel_kematian.setAutoResizeMode(tabel_kematian.AUTO_RESIZE_OFF);    
tabel_kematian.setModel(tabelModel);
try{
Statement state=(Statement)Koneksi.koneksi().createStatement();
ResultSet res=state.executeQuery("select*from data_kematian");
String[] colom={"Id Kematian","NIK","Tanggal Kematian","Pukul","Sebab","Tempat","Info","Ayah","Ibu","Nik Pelapor","Nama Pelapor"};
tabelModel.setDataVector(null,colom);
while(res.next()){
tabelModel.addRow(new Object[]{
res.getString("id_kematian"),
res.getString("nik"),
res.getString("tgl_kematian"),
res.getString("jam_kematian"),
res.getString("sebab_kematian"),
res.getString("tempat_kematian"),
res.getString("yang_menerangkan"),
res.getString("nama_ayah"),
res.getString("nama_ibu"),
res.getString("nik_pelapor"),
res.getString("nama_pelapor"),
} );

}
}catch (Exception e){
JOptionPane.showMessageDialog(rootPane,""+e);
}
new autoresize_tabel().Kolom(tabel_kematian);
tabel_kematian.revalidate(); 
}


   public void data_tabel_jdialog(){
        jTable1.setModel(tabelModel_dialog);
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("select * from penduduk where stts='kosong'");
            String [] kolom={"NIK","Nama"};
            tabelModel_dialog.setDataVector(null, kolom);
            
             while(next_row.next()){
                 tabelModel_dialog.addRow(new Object[] {
                 next_row.getString("nik"),
                 next_row.getString("nama"),
                 
                 
                 });
             }
             
        }catch(Exception e){
    
        }
    }
    
    
    private void simpan(){
        id_mati= txt_id.getText();
        nik = txt_nik.getText();
        String tampil_tgl="yyyy-MM-dd";
        Calendar cal=dateChooserCombo1.getSelectedDate();
        SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
        tgl=String.valueOf(format1.format(cal.getTime()));
        String tampilan ="yyyy-MM-dd" ; 
        
//        String tampilan ="yyyy-MM-dd" ; 
//        String mati="meninggal";
//        SimpleDateFormat fm = new SimpleDateFormat(tampilan); 
//        String tanggal = String.valueOf(fm.format(cbkal.getDate()));
        
        
        String tampil_jam="HH:mm:ss";
        SimpleDateFormat format2=new SimpleDateFormat(tampil_jam);
        jam=String.valueOf(format2.format(spin_time.getValue()));
        
        
        sebab=txt_area.getText();
        tempat=tempat_kematian.getText();
        if(cmb_ket.getSelectedItem().equals("Dokter")){ket="Dokter";}
        else if(cmb_ket.getSelectedItem().equals("Tenaga Kesehatan")){ket="Tenaga Kesehatan";}
        else if(cmb_ket.getSelectedItem().equals("Kepolisian")){ket="Kepolisian";}
        else if(cmb_ket.getSelectedItem().equals("Lainnya")){ket="Lainnya";}
        ayah=txt_ayah.getText();
        ibu=txt_ibu.getText();
        nik_lapor=txt_lapor.getText();
        nama_lapor=txt_nama_lapor.getText();
        
        
    try{
        Statement statement =(Statement)Koneksi.koneksi().createStatement();
        statement.executeUpdate("insert into data_kematian values('"
            +id_mati+"','"
            +nik+"','"
            +tgl+"','"
            +jam+"','"
            +sebab+"','"
            +tempat+"','"
            +ket+"','"
            +ayah+"','"
            +ibu+"','"
            +nik_lapor+"','"    
            +nama_lapor+"');");

        statement.close();
        JOptionPane.showMessageDialog(null,"Data Telah Disimpan....");
        clean();
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,""+e);
        }
              
  
    }
    
    private void clean(){
        txt_id.setText("");
        autonumber();
        txt_nik.setText("");
        tempat_kematian.setText("");
        txt_area.setText("");
        txt_ayah.setText("");
        
       // spin_time.setValue(null);
        txt_ibu.setText("");
        cmb_ket.setSelectedItem("--Keterangan--");
        txt_lapor.setText("");
        txt_nama_lapor.setText("");
        jButton1.setText("save");
    
    }
    
    
private void update() {
        id_mati= txt_id.getText();
        nik = txt_nik.getText();
        String tampil_tgl="yyyy-MM-dd";
        Calendar cal=dateChooserCombo1.getSelectedDate();
        SimpleDateFormat format1=new SimpleDateFormat(tampil_tgl);
        tgl=String.valueOf(format1.format(cal.getTime()));
        
        String tampil_jam="HH:mm:ss";
        SimpleDateFormat format2=new SimpleDateFormat(tampil_jam);
        jam=String.valueOf(format2.format(spin_time.getValue()));
        
        
        sebab=txt_area.getText();
        tempat=tempat_kematian.getText();
        if(cmb_ket.getSelectedItem().equals("Dokter")){ket="Dokter";}
        else if(cmb_ket.getSelectedItem().equals("Tenaga Kesehatan")){ket="Tenaga Kesehatan";}
        else if(cmb_ket.getSelectedItem().equals("Kepolisian")){ket="Kepolisian";}
        else if(cmb_ket.getSelectedItem().equals("Lainnya")){ket="Lainnya";}
        ayah=txt_ayah.getText();
        ibu=txt_ibu.getText();
        nik_lapor=txt_lapor.getText();
        nama_lapor=txt_nama_lapor.getText();
        
        try{

        Statement state =(Statement)Koneksi.koneksi().createStatement();
        state.executeUpdate("UPDATE  data_kematian  SET  nik='"+nik
        +"',"+" tgl_kematian='"+tgl
        +"',"+" jam_kematian='"+jam
        +"',"+" sebab_kematian='"+sebab
        +"',"+" tempat_kematian='"+tempat
        +"',"+" yang_menerangkan='"+ket
        +"',"+" nama_ayah='"+ayah
        +"',"+" nama_ibu='"+ibu
        +"',"+" nik_pelapor='"+nik_lapor
        +"',"+" nama_pelapor='"+nama_lapor
        +"' "+" where id_kematian='"+id_mati+"';");

        state.close();
        JOptionPane.showMessageDialog(null, "Data telah di Ubah. . .");
        } catch(Exception e){
         JOptionPane.showMessageDialog(null, "data gagal di Ubah . . .");
        }
        
    
}

int row=0;
private void tabelklik() throws ParseException{
    row=tabel_kematian.getSelectedRow();
    txt_id.setText(tabel_kematian.getValueAt(row, 0).toString());
    txt_nik.setText(tabel_kematian.getValueAt(row, 1).toString());
    
    tgl = tabel_kematian.getValueAt(row, 2).toString(); 
    java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
    Calendar cal = Calendar.getInstance();
     cal.setTime(date);
     dateChooserCombo1.setSelectedDate(cal);
    
    
    jam = tabel_kematian.getValueAt(row, 3).toString();
    SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
    spin_time.setValue(time.parseObject(jam));
    
    txt_area.setText(tabel_kematian.getValueAt(row, 4).toString());
    tempat_kematian.setText(tabel_kematian.getValueAt(row, 5).toString());
    
    if(tabel_kematian.getValueAt(row, 6).toString().equals("Dokter")){
       cmb_ket.setSelectedItem("Dokter");
    }
    
    else if(tabel_kematian.getValueAt(row, 6).toString().equals("Tenaga Kesehatan")){
       cmb_ket.setSelectedItem("Tenaga Kesehatan");
    }
    
    else if(tabel_kematian.getValueAt(row, 6).toString().equals("Kepolisian")){
       cmb_ket.setSelectedItem("Kepolisian");
    }
    
    else if(tabel_kematian.getValueAt(row, 6).toString().equals("Lainnya")){
       cmb_ket.setSelectedItem("Lainnya");
    }
    
    
    txt_ayah.setText(tabel_kematian.getValueAt(row, 7).toString());
    txt_ibu.setText(tabel_kematian.getValueAt(row, 8).toString());
    txt_lapor.setText(tabel_kematian.getValueAt(row, 9).toString());
    txt_nama_lapor.setText(tabel_kematian.getValueAt(row, 10).toString());
    
    jButton1.setText("save ");

}


  private void hapus (){
          id_mati = txt_id.getText();
         try{
             Statement statement=(Statement)Koneksi.koneksi().createStatement();
             statement.executeUpdate("delete from data_kematian where id_kematian ='"+id_mati+"';");
             statement.close();
             JOptionPane.showMessageDialog(null,"data telah terhapus");
            baru.info_laki();
            baru.info_perempuan();
            baru.info_keluarga();
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"data gagal dihapus");
         }
        
 }
  
public void autonumber() {
        try {
            Statement st =(Statement)Koneksi.koneksi().createStatement();
            String query_bukaTabel="select right(id_kematian,5) as no_urut from data_kematian GROUP BY id_kematian ASC";
            java.sql.ResultSet line_result = st.executeQuery(query_bukaTabel);
            if (line_result.first() == false) {
                txt_id.setText("1");
            } else {
                line_result.last();
                int no = line_result.getInt(1) + 1;
                
                String nomor = String.valueOf(no);
                int oto = nomor.length();
                    String x=nomor;
                txt_id.setText(""+x);
            }
        } catch (Exception e) {
            e.printStackTrace();//penanganan masalah
        }
    }
      
    
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari_nik = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tempat_kematian = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ayah = new javax.swing.JTextField();
        txt_ibu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spin_time = new javax.swing.JSpinner();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        txt_lapor = new javax.swing.JTextField();
        cmb_ket = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txt_nama_lapor = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_kematian = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmb_cari = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txt_cari_nik.setBackground(new java.awt.Color(204, 204, 204));
        txt_cari_nik.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_cari_nik.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton6.setText("cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel25.setText("Nik/ Nama");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txt_cari_nik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1012, 574));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 566));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Kematian");

        clPanelTransparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16_2).png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16).png"))); // NOI18N
        jButton2.setText("clean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setText("Id Kematian");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("NIK");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Tanggal Kematian");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Jam Kematian");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Sebab Kematian");

        txt_nik.setEditable(false);
        txt_nik.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txt_nik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nikMouseClicked(evt);
            }
        });

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Tempat Kematian");

        tempat_kematian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Yang Menerangkan Kematian");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Ayah");

        txt_ayah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_ibu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Ibu");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Nik Pelapor");

        spin_time.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spin_time.setModel(new javax.swing.SpinnerDateModel());
        spin_time.setEditor(new javax.swing.JSpinner.DateEditor(spin_time, "HH:mm:ss"));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane3.setViewportView(txt_area);

        txt_lapor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_lapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_laporMouseClicked(evt);
            }
        });
        txt_lapor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_laporKeyTyped(evt);
            }
        });

        cmb_ket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Keterangan--", "Dokter", "Tenaga Kesehatan", "Kepolisian", "Lainnya" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setText("Nama Pelapor");

        txt_nama_lapor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_nama_lapor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nama_laporMouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/btn_report.png"))); // NOI18N
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        dateChooserCombo1.setNothingAllowed(false);
        dateChooserCombo1.setFormat(0);
        dateChooserCombo1.setFieldFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 12));
        dateChooserCombo1.setLocale(new java.util.Locale("in", "ID", ""));

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel26)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spin_time, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_ket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(66, 66, 66)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tempat_kematian, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_ibu, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_ayah, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_lapor)
                                    .addComponent(txt_nama_lapor)))))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tempat_kematian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cmb_ket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addGap(7, 7, 7))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(txt_ayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_nama_lapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spin_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(20, 20, 20))
        );

        clPanelTransparan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        clPanelTransparan2.setForeground(new java.awt.Color(255, 255, 255));

        tabel_kematian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_kematian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_kematian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_kematian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kematianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_kematian);
        if (tabel_kematian.getColumnModel().getColumnCount() > 0) {
            tabel_kematian.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Cari");

        cmb_cari.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Cari berdasar--", "Nik", "Id Kematian" }));
        cmb_cari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cariItemStateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(29, 29, 29)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(txt_nik.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Klik dahulu pada tabel kematian,pilih No kematian yang dihapus","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        
        else{
         String[] Opsi={"YA","TIDAK"};
        int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Ingin Menghapus Data ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih==JOptionPane.YES_OPTION){
        hapus();
        clean();
        data_tabel();
        lebarKolom();
        
        } else if(Pilih==JOptionPane.NO_OPTION){
              data_tabel();
              lebarKolom();
        }  
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txt_id.getText().equals("")||txt_nik.getText().equals("")
          ||txt_area.getText().equals("")||tempat_kematian.getText().equals("")||cmb_ket.getSelectedItem().equals("--Keterangan--")
          ||txt_ayah.getText().equals("")||txt_ibu.getText().equals("")||txt_lapor.getText().equals("")||txt_nama_lapor.getText().equals("")){
        
            JOptionPane.showMessageDialog(null,"Filed belum dilengkapi");
        }
        
        else{
                if(jButton1.getText().equals("save")){
                    if(txt_lapor.getText().length()<16){JOptionPane.showMessageDialog(null,"NIK kurang dari 16 digit");}
                    else{
                        simpan();
                        data_tabel();
                        lebarKolom();
                    }
                
                }

                else if(jButton1.getText().equals("save ")){
                    String[] Opsi={"YA","TIDAK"};
                    int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Mengubah Data Ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
                    if(Pilih==JOptionPane.YES_OPTION){
                    update();
                    clean();
                    data_tabel();
                    lebarKolom();
                    } else if(Pilih==JOptionPane.NO_OPTION)
                           data_tabel();
                           lebarKolom();
                           baru.info_laki();
                           baru.info_perempuan();
                           baru.info_keluarga();

                }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         String nik1;
         int cek=0;
         String nik = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
         
          jDialog1.setVisible(false);
           
          ResultSet rs;
         try{
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM data_kematian where nik='"+nik+"'");
              nik1=null;
            while (rs.next()){
               nik1=rs.getString("nik");
               if(nik.equals(nik1)){cek=1;}
            }
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
         
         if(cek==1){JOptionPane.showMessageDialog(null,"NIK sudah ada pada data kematian");}
         
         else if(cek!=1){
             txt_nik.setText(nik);
             jDialog1.setVisible(false);
         }
         
         

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(txt_cari_nik.getText().equals("")){JOptionPane.showMessageDialog(null,"Field masih kosong");}
        
        else{
        try
        {
            Statement st = (Statement)Koneksi.koneksi().createStatement();
            String search = txt_cari_nik.getText();
            ResultSet rs = st.executeQuery("SELECT * FROM penduduk WHERE nik like '%"+search+"%' OR nama like '%"+search+"%' AND stts='kosong'");
           // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

            tabelModel_dialog.setRowCount(0);
            String [] data = new String[2];
            int i = 1;

            while(rs.next())
            {
                data[0] = rs.getString("nik");
                data[1] = rs.getString("nama");
                
                tabelModel_dialog.addRow(data);
                i++;
            }
            rs.close();
            //txtcari.setText("");
        }
        catch(Exception ex)  {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        }
        }
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         txt_cari_nik.setText("");
         data_tabel_jdialog();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_kematianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kematianMouseClicked
        // TODO add your handling code here:
        bantu1="1";
       if(evt.getClickCount()==1){
           try {
               tabelklik();
           } catch (ParseException ex) {
               Logger.getLogger(data_kematian.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
    }//GEN-LAST:event_tabel_kematianMouseClicked

    private void cmb_cariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cariItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_cariItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(cmb_cari.getSelectedItem().equals("Nik")){
           
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                     
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kematian WHERE nik like '%"+search+"%'");
                   

                    tabelModel.setRowCount(0);
                    String [] data = new String[10];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("id_kematian");
                        data[1] = rs.getString("nik");
                        data[2] = rs.getString("tgl_kematian");
                        data[3] = rs.getString("jam_kematian");
                        data[4] = rs.getString("sebab_kematian");
                        data[5] = rs.getString("tempat_kematian");
                        data[6] = rs.getString("yang_menerangkan");
                        data[7] = rs.getString("nama_ayah");
                        data[8] = rs.getString("nama_ibu");
                        data[9] = rs.getString("nik_pelapor");
                        
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        
        
        else if(cmb_cari.getSelectedItem().equals("Id Kematian")){
           
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                     
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kematian WHERE id_kematian like '%"+search+"%'");
                   

                    tabelModel.setRowCount(0);
                    String [] data = new String[10];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("id_kematian");
                        data[1] = rs.getString("nik");
                        data[2] = rs.getString("tgl_kematian");
                        data[3] = rs.getString("jam_kematian");
                        data[4] = rs.getString("sebab_kematian");
                        data[5] = rs.getString("tempat_kematian");
                        data[6] = rs.getString("yang_menerangkan");
                        data[7] = rs.getString("nama_ayah");
                        data[8] = rs.getString("nama_ibu");
                        data[9] = rs.getString("nik_pelapor");
                        
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        else{JOptionPane.showMessageDialog(null,"Pilih filter pencarian dahulu");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_nikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nikMouseClicked
        // TODO add your handling code here:
        bantu1="1";
        jDialog1.setLocationRelativeTo(frame);
        jDialog1.setBounds(0,0,472,280);
        data_tabel_jdialog();
        jDialog1.setVisible(true);
    }//GEN-LAST:event_txt_nikMouseClicked

    private void txt_laporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_laporMouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txt_laporMouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        txt_cari.setText("");
        data_tabel();
        lebarKolom();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_nama_laporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nama_laporMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_laporMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Laporan_data_kematian baru= new Laporan_data_kematian();
        baru.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_laporKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_laporKeyTyped
        // TODO add your handling code here:
            char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_lapor.getText().length()==16){evt.consume();}
    
    }//GEN-LAST:event_txt_laporKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JComboBox cmb_ket;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spin_time;
    private javax.swing.JTable tabel_kematian;
    private javax.swing.JTextField tempat_kematian;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_ayah;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_cari_nik;
    private javax.swing.JTextField txt_ibu;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lapor;
    private javax.swing.JTextField txt_nama_lapor;
    private javax.swing.JTextField txt_nik;
    // End of variables declaration//GEN-END:variables
        }
