package Form;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hades
 */
import background.autoresize_tabel;

import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
public class data_kk extends javax.swing.JInternalFrame {
Map param=new HashMap();
JasperReport JasRep;
JasperPrint JasPrint;
JasperDesign JasDes;
    /**
     * Creates new form penduduk
     */
    public data_kk()   {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        
        data_tabel();
        lebarKolom();
      
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      private String no_kk,kk,alamat,rt,rw,kel,kec,kab,kp,prov,aksep,nama_ptgs,nip_ptgs;
      
      private home frame= new home();
      
      private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
        
        return new javax.swing.table.DefaultTableModel(
        new Object [][]{},
        new String[] {"No Kartu Keluarga","Kepala Kelurga","Alamat","RT","RW","Kelurahan","Kecamatan","Kabupaten/Kota","Kode Pos","Provisi","Akseptor"}){ 
        boolean[] canEdit=new boolean[]{
        false,false,false,false,false,false,false,false,false,false,false,
        };
        
        public boolean isCellEdittable(int rowIndex,int coloumnIndex){
            return canEdit[coloumnIndex];
	}
     };
                
   }
      
private void petugas(){
        ResultSet rs;
        String nama="";
        String nip="";
        try{
            
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM petugas WHERE history='masuk'");
            while (rs.next()){
               nama=rs.getString("nama_lengkap");
               nip=rs.getString("nip");
               nama_ptgs=nama;
               nip_ptgs=nip;
            }
        
        }catch(Exception ex)
         {
             
             JOptionPane.showMessageDialog(null,ex);
             
         }
    
}      
                
    
    private javax.swing.table.DefaultTableModel tabelModel=getDefaultTabelModel();
    
    
    private void lebarKolom() {
        TableColumn lebar_kolom;

        

     
        lebar_kolom = tabel_kk.getColumnModel().getColumn(1);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(2);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(3);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(4);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(5);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(6);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(7);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(8);
        lebar_kolom.setPreferredWidth(100);
        lebar_kolom = tabel_kk.getColumnModel().getColumn(9);
        lebar_kolom.setPreferredWidth(100);
         lebar_kolom = tabel_kk.getColumnModel().getColumn(10);
        lebar_kolom.setPreferredWidth(100);


        

    }   
    
private void data_tabel(){
tabel_kk.setAutoResizeMode(tabel_kk.AUTO_RESIZE_OFF);    
tabel_kk.setModel(tabelModel);
try{
Statement state=(Statement)Koneksi.koneksi().createStatement();
ResultSet res=state.executeQuery("select*from data_kk");
String[] colom={"No Kartu Keluarga","Kepala Keluarga","Alamat","RT","RW","Kelurahan","Kecamatan","Kabupaten/Kota","Kode Pos","Provisi","Akseptor"};
tabelModel.setDataVector(null,colom);

while(res.next())
{
tabelModel.addRow(new Object[]{
res.getString("no_kk"),
res.getString("nama_kepala_keluarga"),
res.getString("alamat_kk"),
res.getString("rt"),
res.getString("rw"),
res.getString("desa_kelurahan"),
res.getString("kecamatan"),
res.getString("kabupaten_kota"),
res.getString("kode_pos"),
res.getString("provinsi"),
res.getString("akseptor"),
});

}
}catch (Exception e){
JOptionPane.showMessageDialog(rootPane,""+e);
}
new autoresize_tabel().Kolom(tabel_kk);
tabel_kk.revalidate(); 
}
    
    
    private void simpan(){
        no_kk = txt_kk.getText();
        kk = txt_kepala.getText();
        alamat = txt_alamat.getText();
        rt =txt_rt.getText();
        rw = txt_rw.getText();
        kec = txt_kecamatan.getText();
        kel =txtx_lurah.getText();
        kab = txt_kabupaten.getText();
        kp = txt_kodepos.getText();
        prov= txt_prov.getText();
        aksep="";
        if(cmb_akseptor.getSelectedItem().equals("--Akseptor--")){aksep="kosong";}
        else if(cmb_akseptor.getSelectedItem().equals("Pil")){aksep="Pil";}
        else if(cmb_akseptor.getSelectedItem().equals("IUD")){aksep="IUD";}
        else if(cmb_akseptor.getSelectedItem().equals("Kondom")){aksep="Kondom";}
        else if(cmb_akseptor.getSelectedItem().equals("Suntik")){aksep="Suntik";}
        else if(cmb_akseptor.getSelectedItem().equals("MOP")){aksep="MOP";}
        else if(cmb_akseptor.getSelectedItem().equals("MOW")){aksep="MOW";}
        else if(cmb_akseptor.getSelectedItem().equals("KB Mandiri")){aksep="KB Mandiri";}
        
        
        
    
    try{
        Statement statement =(Statement)Koneksi.koneksi().createStatement();
        statement.executeUpdate("insert into data_kk values('"
            +no_kk+"','"
            +kk+"','"
            +alamat+"','"
            +rt+"','"
            +rw+"','"
            +kel+"','"
            +kec+"','"
            +kab+"','"
            +kp+"','"
            +prov+"','"
            +aksep+"');");

        statement.close();
        JOptionPane.showMessageDialog(null,"Data Telah Disimpan....");
        clean();
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Data Gagal Disimpan....");
        }
              
  
    }
    
    private void clean(){
        txt_kk.enable();
        txt_kk.setText("");
        txt_kepala.setText("");
        txt_alamat.setText("");
        txt_rt.setText("");
        txt_rw.setText("");
        txt_kecamatan.setText("");
        txtx_lurah.setText("");
        txt_kabupaten.setText("");
        txt_kodepos.setText("");
        txt_prov.setText("");
        cmb_akseptor.setSelectedItem("--Akseptor--");
        jButton1.setText("save");
        txt_kk.enable(true);
    
    }
    
    
private void update(){
    no_kk = txt_kk.getText();
    kk = txt_kepala.getText();
    alamat = txt_alamat.getText();
    rt =txt_rt.getText();
    rw = txt_rw.getText();
    kec = txt_kecamatan.getText();
    kel =txtx_lurah.getText();
    kab = txt_kabupaten.getText();
    kp = txt_kodepos.getText();
    prov= txt_prov.getText();
    aksep="";
    if(cmb_akseptor.getSelectedItem().equals("--Akseptor--")){aksep="kosong";}
    else if(cmb_akseptor.getSelectedItem().equals("Pil")){aksep="Pil";}
    else if(cmb_akseptor.getSelectedItem().equals("IUD")){aksep="IUD";}
    else if(cmb_akseptor.getSelectedItem().equals("Kondom")){aksep="Kondom";}
    else if(cmb_akseptor.getSelectedItem().equals("Suntik")){aksep="Suntik";}
    else if(cmb_akseptor.getSelectedItem().equals("MOP")){aksep="MOP";}
    else if(cmb_akseptor.getSelectedItem().equals("MOW")){aksep="MOW";}
    else if(cmb_akseptor.getSelectedItem().equals("KB Mandiri")){aksep="KB Mandiri";}
        
        
try{

    Statement st =(Statement)Koneksi.koneksi().createStatement();
    st.executeUpdate("UPDATE  data_kk  SET  nama_kepala_keluarga='"+kk
    +"',"+" alamat_kk='"+alamat
    +"',"+" rt='"+rt
    +"',"+" rw='"+rw
    +"',"+" desa_kelurahan='"+kel
    +"',"+" kecamatan='"+kec
    +"',"+" kabupaten_kota='"+kab
    +"',"+" kode_pos='"+kp
    +"',"+" provinsi='"+prov
    +"',"+" akseptor='"+aksep        
    +"' "+" where no_kk='"+no_kk+"';");

    st.close();
    JOptionPane.showMessageDialog(null, "Data telah di Ubah. . .");
    clean();
   } catch(Exception e){
     JOptionPane.showMessageDialog(null, "data gagal di Ubah . . .");
    }
        
    
}

int row=0;
private void tabelklik(){
   txt_kk.disable();
   row=tabel_kk.getSelectedRow();
   txt_kk.setText(tabel_kk.getValueAt(row, 0).toString());
   txt_kepala.setText(tabel_kk.getValueAt(row, 1).toString());
   txt_alamat.setText(tabel_kk.getValueAt(row, 2).toString());
   txt_rt.setText(tabel_kk.getValueAt(row, 3).toString());
   txt_rw.setText(tabel_kk.getValueAt(row, 4).toString());
   txt_kecamatan.setText(tabel_kk.getValueAt(row, 6).toString());
   txtx_lurah.setText(tabel_kk.getValueAt(row, 5).toString());
   txt_kabupaten.setText(tabel_kk.getValueAt(row, 7).toString());
   txt_kodepos.setText(tabel_kk.getValueAt(row, 8).toString());
   txt_prov.setText(tabel_kk.getValueAt(row, 9).toString());
   
    if(tabel_kk.getValueAt(row, 10).toString().equals("Pil")){
       cmb_akseptor.setSelectedItem("Pil");
    }
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("IUD")){
        cmb_akseptor.setSelectedItem("IUD");
    }
    
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("Kondom")){
        cmb_akseptor.setSelectedItem("Kondom");
    }  
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("Suntik")){
        cmb_akseptor.setSelectedItem("Suntik");
    }     

    else if(tabel_kk.getValueAt(row, 10).toString().equals("MOP")){
        cmb_akseptor.setSelectedItem("MOP");
    }
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("MOW")){
        cmb_akseptor.setSelectedItem("MOW");
    }
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("KB Mandiri")){
        cmb_akseptor.setSelectedItem("KB Mandiri");
    }
    
    else if(tabel_kk.getValueAt(row, 10).toString().equals("Kosong")||tabel_kk.getValueAt(row, 10).toString().equals("kosong")){
        cmb_akseptor.setSelectedItem("--Akseptor--");
    } 
    
    jButton1.setText("save ");
    txt_kk.disable();



}


  private void hapus (){
         no_kk = txt_kk.getText();
         try{
             Statement statement=(Statement)Koneksi.koneksi().createStatement();
             statement.executeUpdate("delete from data_kk where no_kk ='"+no_kk+"';");
             statement.close();
             JOptionPane.showMessageDialog(null,"data telah terhapus");
         }catch(Exception e){
             JOptionPane.showMessageDialog(null,"data gagal dihapus");
         }
  }
  
    
    
  
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari_kk = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clPanelTransparan1 = new PanelTransparan.ClPanelTransparan();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_kecamatan = new javax.swing.JTextField();
        txt_rw = new javax.swing.JTextField();
        txt_rt = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_kepala = new javax.swing.JTextField();
        txt_kk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtx_lurah = new javax.swing.JTextField();
        txt_kabupaten = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_kodepos = new javax.swing.JTextField();
        txt_prov = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmb_akseptor = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        clPanelTransparan2 = new PanelTransparan.ClPanelTransparan();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_kk = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cmb_cari = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txt_cari_kk.setBackground(new java.awt.Color(204, 204, 204));
        txt_cari_kk.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        txt_cari_kk.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton6.setText("cari");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel25.setText("No KK/ Kepala Keluarga");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txt_cari_kk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1012, 574));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 566));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Data Kartu Keluarga");

        clPanelTransparan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16_2).png"))); // NOI18N
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save(16).png"))); // NOI18N
        jButton2.setText("clean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/delete.png"))); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel26.setText("No KK ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Kepala Keluarga");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("RT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("RW");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("Kecamatan");

        txt_kecamatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_rw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rwKeyTyped(evt);
            }
        });

        txt_rt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_rt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rtKeyTyped(evt);
            }
        });

        txt_alamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_kepala.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_kk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_kk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kkKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kkKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Desa/Kelurahan");

        txtx_lurah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txt_kabupaten.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel9.setText("Kabupaten");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel10.setText("Kode Pos");

        txt_kodepos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_kodepos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kodeposKeyTyped(evt);
            }
        });

        txt_prov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("Provinsi");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setText("Jenis Akseptor");

        cmb_akseptor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_akseptor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Akseptor--", "Pil", "IUD", "Kondom", "Suntik", "MOP", "MOW", "KB Mandiri" }));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report.png"))); // NOI18N
        jButton5.setText("report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan1Layout = new javax.swing.GroupLayout(clPanelTransparan1);
        clPanelTransparan1.setLayout(clPanelTransparan1Layout);
        clPanelTransparan1Layout.setHorizontalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel26)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kk, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kepala, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addComponent(txt_rt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtx_lurah, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_akseptor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        clPanelTransparan1Layout.setVerticalGroup(
            clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_kk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtx_lurah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_kepala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_rt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(txt_rw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(clPanelTransparan1Layout.createSequentialGroup()
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_kabupaten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txt_prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cmb_akseptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(clPanelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(20, 20, 20))
        );

        clPanelTransparan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        tabel_kk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabel_kk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_kk.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_kk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kkMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_kk);
        if (tabel_kk.getColumnModel().getColumnCount() > 0) {
            tabel_kk.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setText("Cari");

        cmb_cari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmb_cari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Cari berdasar--", "Nama", "No KK" }));
        cmb_cari.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_cariItemStateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/search.png"))); // NOI18N
        jButton4.setText("cari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/refresh.png"))); // NOI18N
        jButton10.setText("Refresh");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clPanelTransparan2Layout = new javax.swing.GroupLayout(clPanelTransparan2);
        clPanelTransparan2.setLayout(clPanelTransparan2Layout);
        clPanelTransparan2Layout.setHorizontalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(clPanelTransparan2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(29, 29, 29)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        clPanelTransparan2Layout.setVerticalGroup(
            clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clPanelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clPanelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(cmb_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clPanelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clPanelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(txt_kk.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Klik dahulu pada tabel KK,pilih No KK yang dihapus","Information",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
         String[] Opsi={"YA","TIDAK"};
        int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Ingin Menghapus Data ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih==JOptionPane.YES_OPTION){
        hapus();
        clean();
        data_tabel();
        lebarKolom();
        
        } else if(Pilih==JOptionPane.NO_OPTION){
              data_tabel();
              lebarKolom();
        }
        }  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txt_kk.getText().equals("")||txt_kepala.getText().equals("")||txt_alamat.getText().equals("")
           ||txt_rt.getText().equals("")||txt_rw.getText().equals("")||txtx_lurah.getText().equals("")
           ||txt_kecamatan.getText().equals("")||txt_kabupaten.getText().equals("")||txt_kodepos.getText().equals("")
           ||txt_prov.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Filed belum dilengkapi");
        }
        else{
                if(jButton1.getText().equals("save")){
                    if(txt_kk.getText().length()<16){JOptionPane.showMessageDialog(null,"No KK kurang dari 16 digit");}
                    else if(txt_kodepos.getText().length()<5){JOptionPane.showMessageDialog(null,"Kode pos kurang dari 5 digit");}
                    else{
                        simpan();
                        data_tabel();
                        lebarKolom();
                    }    
                }

                else if(jButton1.getText().equals("save ")){
                    String[] Opsi={"YA","TIDAK"};
                    int Pilih =JOptionPane.showOptionDialog(null,"Anda Yakin Mengubah Data Ini?","Pertanyaan",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
                    if(Pilih==JOptionPane.YES_OPTION){
                    update();
                    clean();
                    data_tabel();
                    lebarKolom();
                    } else if(Pilih==JOptionPane.NO_OPTION)
                           data_tabel();
                           lebarKolom(); 

                }
        }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         txt_cari_kk.setText("");
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clean();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabel_kkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kkMouseClicked
        // TODO add your handling code here:
       if(evt.getClickCount()==1){
            tabelklik();
        }
    }//GEN-LAST:event_tabel_kkMouseClicked

    private void cmb_cariItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_cariItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_cariItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        if(cmb_cari.getSelectedItem().equals("Nama")){
           
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                    
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kk WHERE nama_kepala_keluarga like '%"+search+"%'");
                   // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                    tabelModel.setRowCount(0);
                    String [] data = new String[11];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("no_kk");
                        data[1] = rs.getString("nama_kepala_keluarga");
                        data[2] = rs.getString("alamat_kk");
                        data[3] = rs.getString("rt");
                        data[4] = rs.getString("rw");
                        data[5] = rs.getString("desa_kelurahan");
                        data[6] = rs.getString("kecamatan");
                        data[7] = rs.getString("kabupaten_kota");
                        data[8] = rs.getString("kode_pos");
                        data[9] = rs.getString("provinsi");
                        data[10] = rs.getString("akseptor");
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        
        
        else if(cmb_cari.getSelectedItem().equals("No KK")){
            try
                {
                    Statement st = (Statement)Koneksi.koneksi().createStatement();
                    String search = txt_cari.getText();
                    ResultSet rs = st.executeQuery("SELECT * FROM data_kk WHERE no_kk like '%"+search+"%'");
                   // DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

                    tabelModel.setRowCount(0);
                    String [] data = new String[11];
                    int i = 1;

                    while(rs.next())
                    {
                        data[0] = rs.getString("no_kk");
                        data[1] = rs.getString("nama_kepala_keluarga");
                        data[2] = rs.getString("alamat_kk");
                        data[3] = rs.getString("rt");
                        data[4] = rs.getString("rw");
                        data[5] = rs.getString("desa_kelurahan");
                        data[6] = rs.getString("kecamatan");
                        data[7] = rs.getString("kabupaten_kota");
                        data[8] = rs.getString("kode_pos");
                        data[9] = rs.getString("provinsi");
                        data[10] = rs.getString("akseptor");
                        tabelModel.addRow(data);
                        i++;
                    }
                    rs.close();
                    //txtcari.setText("");
                }
                catch(Exception ex)  {
                    JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
                    System.err.println("error (search) : " +ex);
                }
        
        }
        
        else{JOptionPane.showMessageDialog(null,"Pilih filter pencarian dahulu");}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        txt_cari.setText("");
        cmb_cari.setSelectedIndex(0);
        data_tabel();
        lebarKolom();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        petugas();
        String currentDir = System.getProperty("user.dir");
        java.io.File namaFile=new java.io.File(currentDir+"/src/report/Laporan_data_kk.jrxml");
        try {
            JasDes=JRXmlLoader.load(namaFile);
            param.put("nama_ptgs",nama_ptgs);
            param.put("nip_ptgs",nip_ptgs);
            JasRep=JasperCompileManager.compileReport(JasDes);
            JasPrint=JasperFillManager.fillReport(JasRep,param,Koneksi.koneksi());
            JasperViewer.viewReport(JasPrint,false);
        } catch(JRException|NumberFormatException e){
                       JOptionPane.showMessageDialog(null,e);

        } catch (SQLException ex) {
           Logger.getLogger(Laporan_data_kematian.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_kkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kkKeyReleased
        // TODO add your handling code here:
        ResultSet rs;
         try{
            
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM data_kk");
              kk=null;
              
            while (rs.next()){
          
               kk=rs.getString("no_kk");
               if(txt_kk.getText().equals(kk)){
                   JOptionPane.showMessageDialog(null,"Nomor KK sudah ada");
               }

            }
            
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex);
         }
    }//GEN-LAST:event_txt_kkKeyReleased

    private void txt_kkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kkKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_kk.getText().length()==16){evt.consume();}
    }//GEN-LAST:event_txt_kkKeyTyped

    private void txt_rtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rtKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_rt.getText().length()==3){evt.consume();}
    }//GEN-LAST:event_txt_rtKeyTyped

    private void txt_rwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rwKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_rw.getText().length()==3){evt.consume();}
    }//GEN-LAST:event_txt_rwKeyTyped

    private void txt_kodeposKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kodeposKeyTyped
        // TODO add your handling code here:
         char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
        getToolkit().beep();
        evt.consume();
    }
    else if(txt_kodepos.getText().length()==5){evt.consume();}
    }//GEN-LAST:event_txt_kodeposKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private PanelTransparan.ClPanelTransparan clPanelTransparan1;
    private PanelTransparan.ClPanelTransparan clPanelTransparan2;
    private javax.swing.JComboBox cmb_akseptor;
    private javax.swing.JComboBox cmb_cari;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabel_kk;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_cari_kk;
    private javax.swing.JTextField txt_kabupaten;
    private javax.swing.JTextField txt_kecamatan;
    private javax.swing.JTextField txt_kepala;
    private javax.swing.JTextField txt_kk;
    private javax.swing.JTextField txt_kodepos;
    private javax.swing.JTextField txt_prov;
    private javax.swing.JTextField txt_rt;
    private javax.swing.JTextField txt_rw;
    private javax.swing.JTextField txtx_lurah;
    // End of variables declaration//GEN-END:variables
        }
