package Form;


import com.mysql.jdbc.Statement;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.Koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hades
 */
public final class home extends javax.swing.JFrame {
Map param=new HashMap();
JasperReport JasRep;
JasperPrint JasPrint;
JasperDesign JasDes;
String nama_ptgs,nip_ptgs;
    /**
     * Creates new form home
     */
    String laki,perempuan,keluarga;
    
    public home() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //setDefaultCloseOperation(server.DISPOSE_ON_CLOSE);
        initListener();
        info_laki();
        info_perempuan();
        info_keluarga();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void initListener(){//berfungsi membaca event close frame
        this.addWindowListener(new WindowAdapter(){
        
            @Override
            public void windowClosing(WindowEvent e){
                history();
                
            
            }
        
        
        });
    
    }
   
     private void petugas(){
        ResultSet rs;
        String nama="";
        String nip="";
        try{
            
        Statement st=(Statement)Koneksi.koneksi().createStatement();
            
             rs=st.executeQuery("SELECT * FROM petugas WHERE history='masuk'");
            while (rs.next()){
               nama=rs.getString("nama_lengkap");
               nip=rs.getString("nip");
               nama_ptgs=nama;
               nip_ptgs=nip;
            }
        
        }catch(Exception ex)
         {
             
             JOptionPane.showMessageDialog(null,ex);
             
         }
    
    }
     
     
    private void history(){
        try{
       
        Statement state =(Statement)Koneksi.koneksi().createStatement();
        state.executeUpdate("UPDATE  petugas  SET  history='kosong' where history='masuk';");

        state.close();
        
        
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,""+e);
        }
    }
    
    public void info_laki(){
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("SELECT COUNT(nik) AS jml FROM penduduk  WHERE jk='L' AND stts='kosong'");
           
            
            
             while(next_row.next()){
                 
                 laki=next_row.getString("jml");   
             }
             lbl_laki.setText(laki);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,""+e);
        }
        
    }
    
    public void user(){jMenuItem7.setEnabled(false);}
    public void admin(int i){
        switch(i){
            case 1:
                jMenuItem7.setEnabled(true);
                break;
            case 2:
                jMenuItem7.setEnabled(false);
                break;
            default:
                System.out.println("");
        }
              
        }
    
    
    
     public void info_perempuan(){
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("SELECT COUNT(nik) AS jml FROM penduduk  WHERE jk='P' AND stts='kosong'");
           
            
            
             while(next_row.next()){
                 
                 perempuan=next_row.getString("jml");   
             }
             lbl_perempuan.setText(perempuan);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,""+e);
        }
    
    }
     
     public void info_keluarga(){
        try{
            Statement state=(Statement)Koneksi.koneksi().createStatement();
            ResultSet next_row=state.executeQuery("SELECT COUNT(no_kk) AS jml FROM data_kk");
           
            
            
             while(next_row.next()){
                 
                 keluarga=next_row.getString("jml");   
             }
             lbl_keluarga.setText(keluarga);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,""+e);
        }
    
    } 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_perempuan = new javax.swing.JLabel();
        lbl_keluarga = new javax.swing.JLabel();
        lbl_laki = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        Proses = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        jLabel7.setText("LOGOUT");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo_siak.png"))); // NOI18N
        jLabel8.setText("SIAK");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laki-laki.png"))); // NOI18N
        jLabel1.setText("Laki-Laki :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/keluarga.png"))); // NOI18N
        jLabel4.setText("Keluarga :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/perempuan.png"))); // NOI18N
        jLabel3.setText("Perempuan :");

        lbl_perempuan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_perempuan.setForeground(new java.awt.Color(255, 255, 255));
        lbl_perempuan.setText("0");

        lbl_keluarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_keluarga.setForeground(new java.awt.Color(255, 255, 255));
        lbl_keluarga.setText("0");

        lbl_laki.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_laki.setForeground(new java.awt.Color(255, 255, 255));
        lbl_laki.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/home.png"))); // NOI18N
        jLabel2.setText("Home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_laki)
                .addGap(59, 59, 59)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_perempuan)
                .addGap(76, 76, 76)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_keluarga)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel4)
                .addComponent(jLabel3)
                .addComponent(lbl_perempuan)
                .addComponent(lbl_keluarga)
                .addComponent(lbl_laki)
                .addComponent(jLabel2))
        );

        jDesktopPane2.setBackground(new java.awt.Color(204, 204, 204));
        jDesktopPane2.setPreferredSize(new java.awt.Dimension(994, 570));

        jMenuBar1.setBackground(new java.awt.Color(102, 153, 255));

        jMenu1.setText("Master");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/group.png"))); // NOI18N
        jMenuItem1.setText("Data KK");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penduduk_masuk.png"))); // NOI18N
        jMenuItem2.setText("Penduduk Masuk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report.png"))); // NOI18N
        jMenuItem8.setText("Surat Keterangan");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report.png"))); // NOI18N
        jMenuItem10.setText("Surat Keterangan Domisili");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        Proses.setText("Proses");
        Proses.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kelahiran.png"))); // NOI18N
        jMenuItem3.setText("Kelahiran");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Proses.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kematian.png"))); // NOI18N
        jMenuItem4.setText("Kematian");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Proses.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penduduk_keluar.png"))); // NOI18N
        jMenuItem5.setText("Pindah Penduduk");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Proses.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penduduk_masuk.png"))); // NOI18N
        jMenuItem6.setText("Penduduk Datang");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Proses.add(jMenuItem6);

        jMenuBar1.add(Proses);

        jMenu3.setText("Petugas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pengaturan user.png"))); // NOI18N
        jMenuItem7.setText("Pengaturan Petugas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem9.setText("Report Penduduk");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem11.setText("Report Data KK");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem12.setText("Report Data Kelahiran");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem13.setText("Report Data Kematian");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem14.setText("Report Data Pindah");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/report1.png"))); // NOI18N
        jMenuItem15.setText("Report Data Datang");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Object[] options={"ya","tidak"}; 
        int nilai=JOptionPane.showOptionDialog(this,"apakah yakin anda akan keluar dari sistem?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,options,options[1]);
        
        if(nilai==0){
            history();
            this.dispose();
            Login baru=new Login();
            baru.setVisible(true);
        }
        
        
        
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
        
        penduduk baru=new penduduk();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
        data_kk baru= new data_kk();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
        data_kematian baru= new data_kematian();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
         data_datang baru= new data_datang();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
        data_kelahiran baru= new data_kelahiran();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
         data_pindah baru= new data_pindah();
        jDesktopPane2.removeAll();
        jDesktopPane2.updateUI();
        jDesktopPane2.add(baru);
        baru.setVisible(true);
        try {
            baru.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        info_keluarga();
        info_laki();
        info_perempuan();
         daftar_petugas baru= new daftar_petugas();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        surat_pengantar baru =new surat_pengantar();
        baru.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        surat_ket_domisili baru = new surat_ket_domisili();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        petugas();
        String currentDir = System.getProperty("user.dir");
        java.io.File namaFile=new java.io.File(currentDir+"/src/report/Laporan_penduduk.jrxml");
        try {
            JasDes=JRXmlLoader.load(namaFile);
            param.put("nama_ptgs",nama_ptgs);
            param.put("nip_ptgs",nip_ptgs);
            JasRep=JasperCompileManager.compileReport(JasDes);
            JasPrint=JasperFillManager.fillReport(JasRep,param,Koneksi.koneksi());
            JasperViewer.viewReport(JasPrint,false);
        } catch(JRException|NumberFormatException e){
                       JOptionPane.showMessageDialog(null,e);

        } catch (SQLException ex) {
           Logger.getLogger(Laporan_data_kematian.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        petugas();
        String currentDir = System.getProperty("user.dir");
        java.io.File namaFile=new java.io.File(currentDir+"/src/report/Laporan_data_kk.jrxml");
        try {
            JasDes=JRXmlLoader.load(namaFile);
            param.put("nama_ptgs",nama_ptgs);
            param.put("nip_ptgs",nip_ptgs);
            JasRep=JasperCompileManager.compileReport(JasDes);
            JasPrint=JasperFillManager.fillReport(JasRep,param,Koneksi.koneksi());
            JasperViewer.viewReport(JasPrint,false);
        } catch(JRException|NumberFormatException e){
                       JOptionPane.showMessageDialog(null,e);

        } catch (SQLException ex) {
           Logger.getLogger(Laporan_data_kematian.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        Laporan_data_kelahiran baru= new Laporan_data_kelahiran();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         Laporan_data_kematian baru= new Laporan_data_kematian();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
         Laporan_data_pindah baru= new Laporan_data_pindah();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
         Laporan_data_datang baru= new Laporan_data_datang();
        baru.setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Proses;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbl_keluarga;
    private javax.swing.JLabel lbl_laki;
    private javax.swing.JLabel lbl_perempuan;
    // End of variables declaration//GEN-END:variables
}
